module Game
  class MapGroup
    MAP_BATTLE_COLOSSEUM_2P = 'MAP_BATTLE_COLOSSEUM_2P'.freeze
    MAP_TRADE_CENTER = 'MAP_TRADE_CENTER '.freeze
    MAP_RECORD_CORNER = 'MAP_RECORD_CORNER '.freeze
    MAP_BATTLE_COLOSSEUM_4P = 'MAP_BATTLE_COLOSSEUM_4P'.freeze
    MAP_UNION_ROOM = 'MAP_UNION_ROOM '.freeze
    MAP_VIRIDIAN_FOREST = 'MAP_VIRIDIAN_FOREST '.freeze
    MAP_MT_MOON_1F = 'MAP_MT_MOON_1F '.freeze
    MAP_MT_MOON_B1F  = 'MAP_MT_MOON_B1F '.freeze
    MAP_MT_MOON_B2F  = 'MAP_MT_MOON_B2F '.freeze
    MAP_SSANNE_EXTERIOR = 'MAP_SSANNE_EXTERIOR '.freeze
    MAP_SSANNE_1F_CORRIDOR  = 'MAP_SSANNE_1F_CORRIDOR '.freeze
    MAP_SSANNE_2F_CORRIDOR  = 'MAP_SSANNE_2F_CORRIDOR '.freeze
    MAP_SSANNE_3F_CORRIDOR  = 'MAP_SSANNE_3F_CORRIDOR '.freeze
    MAP_SSANNE_B1F_CORRIDOR = 'MAP_SSANNE_B1F_CORRIDOR '.freeze
    MAP_SSANNE_DECK = 'MAP_SSANNE_DECK '.freeze
    MAP_SSANNE_KITCHEN = 'MAP_SSANNE_KITCHEN '.freeze
    MAP_SSANNE_CAPTAINS_OFFICE = 'MAP_SSANNE_CAPTAINS_OFFICE '.freeze
    MAP_SSANNE_1F_ROOM1  = 'MAP_SSANNE_1F_ROOM1 '.freeze
    MAP_SSANNE_1F_ROOM2  = 'MAP_SSANNE_1F_ROOM2 '.freeze
    MAP_SSANNE_1F_ROOM3  = 'MAP_SSANNE_1F_ROOM3 '.freeze
    MAP_SSANNE_1F_ROOM4  = 'MAP_SSANNE_1F_ROOM4 '.freeze
    MAP_SSANNE_1F_ROOM5  = 'MAP_SSANNE_1F_ROOM5 '.freeze
    MAP_SSANNE_1F_ROOM7  = 'MAP_SSANNE_1F_ROOM7 '.freeze
    MAP_SSANNE_2F_ROOM1  = 'MAP_SSANNE_2F_ROOM1 '.freeze
    MAP_SSANNE_2F_ROOM2  = 'MAP_SSANNE_2F_ROOM2 '.freeze
    MAP_SSANNE_2F_ROOM3  = 'MAP_SSANNE_2F_ROOM3 '.freeze
    MAP_SSANNE_2F_ROOM4  = 'MAP_SSANNE_2F_ROOM4 '.freeze
    MAP_SSANNE_2F_ROOM5  = 'MAP_SSANNE_2F_ROOM5 '.freeze
    MAP_SSANNE_2F_ROOM6  = 'MAP_SSANNE_2F_ROOM6 '.freeze
    MAP_SSANNE_B1F_ROOM1  = 'MAP_SSANNE_B1F_ROOM1 '.freeze
    MAP_SSANNE_B1F_ROOM2  = 'MAP_SSANNE_B1F_ROOM2 '.freeze
    MAP_SSANNE_B1F_ROOM3  = 'MAP_SSANNE_B1F_ROOM3 '.freeze
    MAP_SSANNE_B1F_ROOM4  = 'MAP_SSANNE_B1F_ROOM4 '.freeze
    MAP_SSANNE_B1F_ROOM5  = 'MAP_SSANNE_B1F_ROOM5 '.freeze
    MAP_SSANNE_1F_ROOM6 = 'MAP_SSANNE_1F_ROOM6 '.freeze
    MAP_UNDERGROUND_PATH_NORTH_ENTRANCE = 'MAP_UNDERGROUND_PATH_NORTH_ENTRANCE '.freeze
    MAP_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL = 'MAP_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL '.freeze
    MAP_UNDERGROUND_PATH_SOUTH_ENTRANCE = 'MAP_UNDERGROUND_PATH_SOUTH_ENTRANCE '.freeze
    MAP_UNDERGROUND_PATH_WEST_ENTRANCE = 'MAP_UNDERGROUND_PATH_WEST_ENTRANCE '.freeze
    MAP_UNDERGROUND_PATH_EAST_WEST_TUNNEL = 'MAP_UNDERGROUND_PATH_EAST_WEST_TUNNEL '.freeze
    MAP_UNDERGROUND_PATH_EAST_ENTRANCE = 'MAP_UNDERGROUND_PATH_EAST_ENTRANCE '.freeze
    MAP_DIGLETTS_CAVE_NORTH_ENTRANCE = 'MAP_DIGLETTS_CAVE_NORTH_ENTRANCE '.freeze
    MAP_DIGLETTS_CAVE_B1F = 'MAP_DIGLETTS_CAVE_B1F '.freeze
    MAP_DIGLETTS_CAVE_SOUTH_ENTRANCE = 'MAP_DIGLETTS_CAVE_SOUTH_ENTRANCE '.freeze
    MAP_VICTORY_ROAD_1F  = 'MAP_VICTORY_ROAD_1F '.freeze
    MAP_VICTORY_ROAD_2F  = 'MAP_VICTORY_ROAD_2F '.freeze
    MAP_VICTORY_ROAD_3F  = 'MAP_VICTORY_ROAD_3F '.freeze
    MAP_ROCKET_HIDEOUT_B1F  = 'MAP_ROCKET_HIDEOUT_B1F '.freeze
    MAP_ROCKET_HIDEOUT_B2F  = 'MAP_ROCKET_HIDEOUT_B2F '.freeze
    MAP_ROCKET_HIDEOUT_B3F  = 'MAP_ROCKET_HIDEOUT_B3F '.freeze
    MAP_ROCKET_HIDEOUT_B4F  = 'MAP_ROCKET_HIDEOUT_B4F '.freeze
    MAP_ROCKET_HIDEOUT_ELEVATOR = 'MAP_ROCKET_HIDEOUT_ELEVATOR '.freeze
    MAP_SILPH_CO_1F  = 'MAP_SILPH_CO_1F '.freeze
    MAP_SILPH_CO_2F  = 'MAP_SILPH_CO_2F '.freeze
    MAP_SILPH_CO_3F  = 'MAP_SILPH_CO_3F '.freeze
    MAP_SILPH_CO_4F  = 'MAP_SILPH_CO_4F '.freeze
    MAP_SILPH_CO_5F  = 'MAP_SILPH_CO_5F '.freeze
    MAP_SILPH_CO_6F  = 'MAP_SILPH_CO_6F '.freeze
    MAP_SILPH_CO_7F  = 'MAP_SILPH_CO_7F '.freeze
    MAP_SILPH_CO_8F  = 'MAP_SILPH_CO_8F '.freeze
    MAP_SILPH_CO_9F  = 'MAP_SILPH_CO_9F '.freeze
    MAP_SILPH_CO_10F  = 'MAP_SILPH_CO_10F '.freeze
    MAP_SILPH_CO_11F  = 'MAP_SILPH_CO_11F '.freeze
    MAP_SILPH_CO_ELEVATOR = 'MAP_SILPH_CO_ELEVATOR '.freeze
    MAP_POKEMON_MANSION_1F  = 'MAP_POKEMON_MANSION_1F '.freeze
    MAP_POKEMON_MANSION_2F  = 'MAP_POKEMON_MANSION_2F '.freeze
    MAP_POKEMON_MANSION_3F  = 'MAP_POKEMON_MANSION_3F '.freeze
    MAP_POKEMON_MANSION_B1F = 'MAP_POKEMON_MANSION_B1F '.freeze
    MAP_SAFARI_ZONE_CENTER = 'MAP_SAFARI_ZONE_CENTER '.freeze
    MAP_SAFARI_ZONE_EAST = 'MAP_SAFARI_ZONE_EAST '.freeze
    MAP_SAFARI_ZONE_NORTH = 'MAP_SAFARI_ZONE_NORTH '.freeze
    MAP_SAFARI_ZONE_WEST = 'MAP_SAFARI_ZONE_WEST '.freeze
    MAP_SAFARI_ZONE_CENTER_REST_HOUSE = 'MAP_SAFARI_ZONE_CENTER_REST_HOUSE '.freeze
    MAP_SAFARI_ZONE_EAST_REST_HOUSE = 'MAP_SAFARI_ZONE_EAST_REST_HOUSE '.freeze
    MAP_SAFARI_ZONE_NORTH_REST_HOUSE = 'MAP_SAFARI_ZONE_NORTH_REST_HOUSE '.freeze
    MAP_SAFARI_ZONE_WEST_REST_HOUSE = 'MAP_SAFARI_ZONE_WEST_REST_HOUSE '.freeze
    MAP_SAFARI_ZONE_SECRET_HOUSE = 'MAP_SAFARI_ZONE_SECRET_HOUSE '.freeze
    MAP_CERULEAN_CAVE_1F  = 'MAP_CERULEAN_CAVE_1F '.freeze
    MAP_CERULEAN_CAVE_2F  = 'MAP_CERULEAN_CAVE_2F '.freeze
    MAP_CERULEAN_CAVE_B1F = 'MAP_CERULEAN_CAVE_B1F '.freeze
    MAP_POKEMON_LEAGUE_LORELEIS_ROOM = 'MAP_POKEMON_LEAGUE_LORELEIS_ROOM '.freeze
    MAP_POKEMON_LEAGUE_BRUNOS_ROOM = 'MAP_POKEMON_LEAGUE_BRUNOS_ROOM '.freeze
    MAP_POKEMON_LEAGUE_AGATHAS_ROOM = 'MAP_POKEMON_LEAGUE_AGATHAS_ROOM '.freeze
    MAP_POKEMON_LEAGUE_LANCES_ROOM = 'MAP_POKEMON_LEAGUE_LANCES_ROOM '.freeze
    MAP_POKEMON_LEAGUE_CHAMPIONS_ROOM = 'MAP_POKEMON_LEAGUE_CHAMPIONS_ROOM '.freeze
    MAP_POKEMON_LEAGUE_HALL_OF_FAME = 'MAP_POKEMON_LEAGUE_HALL_OF_FAME '.freeze
    MAP_ROCK_TUNNEL_1F = 'MAP_ROCK_TUNNEL_1F '.freeze
    MAP_ROCK_TUNNEL_B1F = 'MAP_ROCK_TUNNEL_B1F '.freeze
    MAP_SEAFOAM_ISLANDS_1F = 'MAP_SEAFOAM_ISLANDS_1F '.freeze
    MAP_SEAFOAM_ISLANDS_B1F  = 'MAP_SEAFOAM_ISLANDS_B1F '.freeze
    MAP_SEAFOAM_ISLANDS_B2F  = 'MAP_SEAFOAM_ISLANDS_B2F '.freeze
    MAP_SEAFOAM_ISLANDS_B3F  = 'MAP_SEAFOAM_ISLANDS_B3F '.freeze
    MAP_SEAFOAM_ISLANDS_B4F  = 'MAP_SEAFOAM_ISLANDS_B4F '.freeze
    MAP_POKEMON_TOWER_1F  = 'MAP_POKEMON_TOWER_1F '.freeze
    MAP_POKEMON_TOWER_2F  = 'MAP_POKEMON_TOWER_2F '.freeze
    MAP_POKEMON_TOWER_3F  = 'MAP_POKEMON_TOWER_3F '.freeze
    MAP_POKEMON_TOWER_4F  = 'MAP_POKEMON_TOWER_4F '.freeze
    MAP_POKEMON_TOWER_5F  = 'MAP_POKEMON_TOWER_5F '.freeze
    MAP_POKEMON_TOWER_6F  = 'MAP_POKEMON_TOWER_6F '.freeze
    MAP_POKEMON_TOWER_7F  = 'MAP_POKEMON_TOWER_7F '.freeze
    MAP_POWER_PLANT = 'MAP_POWER_PLANT '.freeze
    MAP_MT_EMBER_RUBY_PATH_B4F = 'MAP_MT_EMBER_RUBY_PATH_B4F '.freeze
    MAP_MT_EMBER_EXTERIOR = 'MAP_MT_EMBER_EXTERIOR '.freeze
    MAP_MT_EMBER_SUMMIT_PATH_1F  = 'MAP_MT_EMBER_SUMMIT_PATH_1F '.freeze
    MAP_MT_EMBER_SUMMIT_PATH_2F  = 'MAP_MT_EMBER_SUMMIT_PATH_2F '.freeze
    MAP_MT_EMBER_SUMMIT_PATH_3F  = 'MAP_MT_EMBER_SUMMIT_PATH_3F '.freeze
    MAP_MT_EMBER_SUMMIT = 'MAP_MT_EMBER_SUMMIT '.freeze
    MAP_MT_EMBER_RUBY_PATH_B5F = 'MAP_MT_EMBER_RUBY_PATH_B5F '.freeze
    MAP_MT_EMBER_RUBY_PATH_1F = 'MAP_MT_EMBER_RUBY_PATH_1F '.freeze
    MAP_MT_EMBER_RUBY_PATH_B1F  = 'MAP_MT_EMBER_RUBY_PATH_B1F '.freeze
    MAP_MT_EMBER_RUBY_PATH_B2F  = 'MAP_MT_EMBER_RUBY_PATH_B2F '.freeze
    MAP_MT_EMBER_RUBY_PATH_B3F  = 'MAP_MT_EMBER_RUBY_PATH_B3F '.freeze
    MAP_MT_EMBER_RUBY_PATH_B1F_STAIRS  = 'MAP_MT_EMBER_RUBY_PATH_B1F_STAIRS '.freeze
    MAP_MT_EMBER_RUBY_PATH_B2F_STAIRS  = 'MAP_MT_EMBER_RUBY_PATH_B2F_STAIRS '.freeze
    MAP_THREE_ISLAND_BERRY_FOREST = 'MAP_THREE_ISLAND_BERRY_FOREST '.freeze
    MAP_FOUR_ISLAND_ICEFALL_CAVE_ENTRANCE = 'MAP_FOUR_ISLAND_ICEFALL_CAVE_ENTRANCE '.freeze
    MAP_FOUR_ISLAND_ICEFALL_CAVE_1F = 'MAP_FOUR_ISLAND_ICEFALL_CAVE_1F '.freeze
    MAP_FOUR_ISLAND_ICEFALL_CAVE_B1F = 'MAP_FOUR_ISLAND_ICEFALL_CAVE_B1F '.freeze
    MAP_FOUR_ISLAND_ICEFALL_CAVE_BACK = 'MAP_FOUR_ISLAND_ICEFALL_CAVE_BACK '.freeze
    MAP_FIVE_ISLAND_ROCKET_WAREHOUSE = 'MAP_FIVE_ISLAND_ROCKET_WAREHOUSE '.freeze
    MAP_SIX_ISLAND_DOTTED_HOLE_1F = 'MAP_SIX_ISLAND_DOTTED_HOLE_1F '.freeze
    MAP_SIX_ISLAND_DOTTED_HOLE_B1F  = 'MAP_SIX_ISLAND_DOTTED_HOLE_B1F '.freeze
    MAP_SIX_ISLAND_DOTTED_HOLE_B2F  = 'MAP_SIX_ISLAND_DOTTED_HOLE_B2F '.freeze
    MAP_SIX_ISLAND_DOTTED_HOLE_B3F  = 'MAP_SIX_ISLAND_DOTTED_HOLE_B3F '.freeze
    MAP_SIX_ISLAND_DOTTED_HOLE_B4F  = 'MAP_SIX_ISLAND_DOTTED_HOLE_B4F '.freeze
    MAP_SIX_ISLAND_DOTTED_HOLE_SAPPHIRE_ROOM = 'MAP_SIX_ISLAND_DOTTED_HOLE_SAPPHIRE_ROOM'.freeze
    MAP_SIX_ISLAND_PATTERN_BUSH = 'MAP_SIX_ISLAND_PATTERN_BUSH '.freeze
    MAP_SIX_ISLAND_ALTERING_CAVE = 'MAP_SIX_ISLAND_ALTERING_CAVE '.freeze
    MAP_NAVEL_ROCK_EXTERIOR = 'MAP_NAVEL_ROCK_EXTERIOR '.freeze
    MAP_TRAINER_TOWER_1F  = 'MAP_TRAINER_TOWER_1F '.freeze
    MAP_TRAINER_TOWER_2F  = 'MAP_TRAINER_TOWER_2F '.freeze
    MAP_TRAINER_TOWER_3F  = 'MAP_TRAINER_TOWER_3F '.freeze
    MAP_TRAINER_TOWER_4F  = 'MAP_TRAINER_TOWER_4F '.freeze
    MAP_TRAINER_TOWER_5F  = 'MAP_TRAINER_TOWER_5F '.freeze
    MAP_TRAINER_TOWER_6F  = 'MAP_TRAINER_TOWER_6F '.freeze
    MAP_TRAINER_TOWER_7F  = 'MAP_TRAINER_TOWER_7F '.freeze
    MAP_TRAINER_TOWER_8F  = 'MAP_TRAINER_TOWER_8F '.freeze
    MAP_TRAINER_TOWER_ROOF = 'MAP_TRAINER_TOWER_ROOF '.freeze
    MAP_TRAINER_TOWER_LOBBY = 'MAP_TRAINER_TOWER_LOBBY '.freeze
    MAP_TRAINER_TOWER_ELEVATOR = 'MAP_TRAINER_TOWER_ELEVATOR '.freeze
    MAP_FIVE_ISLAND_LOST_CAVE_ENTRANCE = 'MAP_FIVE_ISLAND_LOST_CAVE_ENTRANCE '.freeze
    MAP_FIVE_ISLAND_LOST_CAVE_ROOM1  = 'MAP_FIVE_ISLAND_LOST_CAVE_ROOM1 '.freeze
    MAP_FIVE_ISLAND_LOST_CAVE_ROOM2  = 'MAP_FIVE_ISLAND_LOST_CAVE_ROOM2 '.freeze
    MAP_FIVE_ISLAND_LOST_CAVE_ROOM3  = 'MAP_FIVE_ISLAND_LOST_CAVE_ROOM3 '.freeze
    MAP_FIVE_ISLAND_LOST_CAVE_ROOM4  = 'MAP_FIVE_ISLAND_LOST_CAVE_ROOM4 '.freeze
    MAP_FIVE_ISLAND_LOST_CAVE_ROOM5  = 'MAP_FIVE_ISLAND_LOST_CAVE_ROOM5 '.freeze
    MAP_FIVE_ISLAND_LOST_CAVE_ROOM6  = 'MAP_FIVE_ISLAND_LOST_CAVE_ROOM6 '.freeze
    MAP_FIVE_ISLAND_LOST_CAVE_ROOM7  = 'MAP_FIVE_ISLAND_LOST_CAVE_ROOM7 '.freeze
    MAP_FIVE_ISLAND_LOST_CAVE_ROOM8  = 'MAP_FIVE_ISLAND_LOST_CAVE_ROOM8 '.freeze
    MAP_FIVE_ISLAND_LOST_CAVE_ROOM9  = 'MAP_FIVE_ISLAND_LOST_CAVE_ROOM9 '.freeze
    MAP_FIVE_ISLAND_LOST_CAVE_ROOM10  = 'MAP_FIVE_ISLAND_LOST_CAVE_ROOM10 '.freeze
    MAP_FIVE_ISLAND_LOST_CAVE_ROOM11  = 'MAP_FIVE_ISLAND_LOST_CAVE_ROOM11 '.freeze
    MAP_FIVE_ISLAND_LOST_CAVE_ROOM12  = 'MAP_FIVE_ISLAND_LOST_CAVE_ROOM12 '.freeze
    MAP_FIVE_ISLAND_LOST_CAVE_ROOM13  = 'MAP_FIVE_ISLAND_LOST_CAVE_ROOM13 '.freeze
    MAP_FIVE_ISLAND_LOST_CAVE_ROOM14  = 'MAP_FIVE_ISLAND_LOST_CAVE_ROOM14 '.freeze
    MAP_SEVEN_ISLAND_TANOBY_RUINS_MONEAN_CHAMBER  = 'MAP_SEVEN_ISLAND_TANOBY_RUINS_MONEAN_CHAMBER '.freeze
    MAP_SEVEN_ISLAND_TANOBY_RUINS_LIPTOO_CHAMBER  = 'MAP_SEVEN_ISLAND_TANOBY_RUINS_LIPTOO_CHAMBER '.freeze
    MAP_SEVEN_ISLAND_TANOBY_RUINS_WEEPTH_CHAMBER  = 'MAP_SEVEN_ISLAND_TANOBY_RUINS_WEEPTH_CHAMBER '.freeze
    MAP_SEVEN_ISLAND_TANOBY_RUINS_DILFORD_CHAMBER = 'MAP_SEVEN_ISLAND_TANOBY_RUINS_DILFORD_CHAMBER'.freeze
    MAP_SEVEN_ISLAND_TANOBY_RUINS_SCUFIB_CHAMBER  = 'MAP_SEVEN_ISLAND_TANOBY_RUINS_SCUFIB_CHAMBER '.freeze
    MAP_SEVEN_ISLAND_TANOBY_RUINS_RIXY_CHAMBER = 'MAP_SEVEN_ISLAND_TANOBY_RUINS_RIXY_CHAMBER '.freeze
    MAP_SEVEN_ISLAND_TANOBY_RUINS_VIAPOIS_CHAMBER = 'MAP_SEVEN_ISLAND_TANOBY_RUINS_VIAPOIS_CHAMBER'.freeze
    MAP_THREE_ISLAND_DUNSPARCE_TUNNEL = 'MAP_THREE_ISLAND_DUNSPARCE_TUNNEL '.freeze
    MAP_SEVEN_ISLAND_SEVAULT_CANYON_TANOBY_KEY = 'MAP_SEVEN_ISLAND_SEVAULT_CANYON_TANOBY_KEY '.freeze
    MAP_NAVEL_ROCK_1F = 'MAP_NAVEL_ROCK_1F '.freeze
    MAP_NAVEL_ROCK_SUMMIT = 'MAP_NAVEL_ROCK_SUMMIT '.freeze
    MAP_NAVEL_ROCK_BASE = 'MAP_NAVEL_ROCK_BASE '.freeze
    MAP_NAVEL_ROCK_SUMMIT_PATH_2F  = 'MAP_NAVEL_ROCK_SUMMIT_PATH_2F '.freeze
    MAP_NAVEL_ROCK_SUMMIT_PATH_3F  = 'MAP_NAVEL_ROCK_SUMMIT_PATH_3F '.freeze
    MAP_NAVEL_ROCK_SUMMIT_PATH_4F  = 'MAP_NAVEL_ROCK_SUMMIT_PATH_4F '.freeze
    MAP_NAVEL_ROCK_SUMMIT_PATH_5F  = 'MAP_NAVEL_ROCK_SUMMIT_PATH_5F '.freeze
    MAP_NAVEL_ROCK_BASE_PATH_B1F  = 'MAP_NAVEL_ROCK_BASE_PATH_B1F '.freeze
    MAP_NAVEL_ROCK_BASE_PATH_B2F  = 'MAP_NAVEL_ROCK_BASE_PATH_B2F '.freeze
    MAP_NAVEL_ROCK_BASE_PATH_B3F  = 'MAP_NAVEL_ROCK_BASE_PATH_B3F '.freeze
    MAP_NAVEL_ROCK_BASE_PATH_B4F  = 'MAP_NAVEL_ROCK_BASE_PATH_B4F '.freeze
    MAP_NAVEL_ROCK_BASE_PATH_B5F  = 'MAP_NAVEL_ROCK_BASE_PATH_B5F '.freeze
    MAP_NAVEL_ROCK_BASE_PATH_B6F  = 'MAP_NAVEL_ROCK_BASE_PATH_B6F '.freeze
    MAP_NAVEL_ROCK_BASE_PATH_B7F  = 'MAP_NAVEL_ROCK_BASE_PATH_B7F '.freeze
    MAP_NAVEL_ROCK_BASE_PATH_B8F  = 'MAP_NAVEL_ROCK_BASE_PATH_B8F '.freeze
    MAP_NAVEL_ROCK_BASE_PATH_B9F  = 'MAP_NAVEL_ROCK_BASE_PATH_B9F '.freeze
    MAP_NAVEL_ROCK_BASE_PATH_B10F  = 'MAP_NAVEL_ROCK_BASE_PATH_B10F '.freeze
    MAP_NAVEL_ROCK_BASE_PATH_B11F  = 'MAP_NAVEL_ROCK_BASE_PATH_B11F '.freeze
    MAP_NAVEL_ROCK_B1F = 'MAP_NAVEL_ROCK_B1F '.freeze
    MAP_NAVEL_ROCK_FORK = 'MAP_NAVEL_ROCK_FORK '.freeze
    MAP_BIRTH_ISLAND_EXTERIOR = 'MAP_BIRTH_ISLAND_EXTERIOR '.freeze
    MAP_ONE_ISLAND_KINDLE_ROAD_EMBER_SPA = 'MAP_ONE_ISLAND_KINDLE_ROAD_EMBER_SPA '.freeze
    MAP_BIRTH_ISLAND_HARBOR = 'MAP_BIRTH_ISLAND_HARBOR '.freeze
    MAP_NAVEL_ROCK_HARBOR = 'MAP_NAVEL_ROCK_HARBOR '.freeze
    MAP_PALLET_TOWN = 'MAP_PALLET_TOWN '.freeze
    MAP_VIRIDIAN_CITY = 'MAP_VIRIDIAN_CITY '.freeze
    MAP_PEWTER_CITY = 'MAP_PEWTER_CITY '.freeze
    MAP_CERULEAN_CITY  = 'MAP_CERULEAN_CITY '.freeze
    MAP_LAVENDER_TOWN  = 'MAP_LAVENDER_TOWN '.freeze
    MAP_VERMILION_CITY = 'MAP_VERMILION_CITY '.freeze
    MAP_CELADON_CITY  = 'MAP_CELADON_CITY '.freeze
    MAP_FUCHSIA_CITY  = 'MAP_FUCHSIA_CITY '.freeze
    MAP_CINNABAR_ISLAND = 'MAP_CINNABAR_ISLAND '.freeze
    MAP_INDIGO_PLATEAU_EXTERIOR = 'MAP_INDIGO_PLATEAU_EXTERIOR '.freeze
    MAP_SAFFRON_CITY = 'MAP_SAFFRON_CITY '.freeze
    MAP_SAFFRON_CITY_CONNECTION = 'MAP_SAFFRON_CITY_CONNECTION '.freeze
    MAP_ONE_ISLAND  = 'MAP_ONE_ISLAND '.freeze
    MAP_TWO_ISLAND  = 'MAP_TWO_ISLAND '.freeze
    MAP_THREE_ISLAND = 'MAP_THREE_ISLAND '.freeze
    MAP_FOUR_ISLAND  = 'MAP_FOUR_ISLAND '.freeze
    MAP_FIVE_ISLAND  = 'MAP_FIVE_ISLAND '.freeze
    MAP_SEVEN_ISLAND = 'MAP_SEVEN_ISLAND '.freeze
    MAP_SIX_ISLAND = 'MAP_SIX_ISLAND '.freeze
    MAP_ROUTE1  = 'MAP_ROUTE1 '.freeze
    MAP_ROUTE2  = 'MAP_ROUTE2 '.freeze
    MAP_ROUTE3  = 'MAP_ROUTE3 '.freeze
    MAP_ROUTE4  = 'MAP_ROUTE4 '.freeze
    MAP_ROUTE5  = 'MAP_ROUTE5 '.freeze
    MAP_ROUTE6  = 'MAP_ROUTE6 '.freeze
    MAP_ROUTE7  = 'MAP_ROUTE7 '.freeze
    MAP_ROUTE8  = 'MAP_ROUTE8 '.freeze
    MAP_ROUTE9  = 'MAP_ROUTE9 '.freeze
    MAP_ROUTE10  = 'MAP_ROUTE10 '.freeze
    MAP_ROUTE11  = 'MAP_ROUTE11 '.freeze
    MAP_ROUTE12  = 'MAP_ROUTE12 '.freeze
    MAP_ROUTE13  = 'MAP_ROUTE13 '.freeze
    MAP_ROUTE14  = 'MAP_ROUTE14 '.freeze
    MAP_ROUTE15  = 'MAP_ROUTE15 '.freeze
    MAP_ROUTE16  = 'MAP_ROUTE16 '.freeze
    MAP_ROUTE17  = 'MAP_ROUTE17 '.freeze
    MAP_ROUTE18  = 'MAP_ROUTE18 '.freeze
    MAP_ROUTE19  = 'MAP_ROUTE19 '.freeze
    MAP_ROUTE20  = 'MAP_ROUTE20 '.freeze
    MAP_ROUTE21_NORTH  = 'MAP_ROUTE21_NORTH '.freeze
    MAP_ROUTE21_SOUTH  = 'MAP_ROUTE21_SOUTH '.freeze
    MAP_ROUTE22  = 'MAP_ROUTE22 '.freeze
    MAP_ROUTE23  = 'MAP_ROUTE23 '.freeze
    MAP_ROUTE24  = 'MAP_ROUTE24 '.freeze
    MAP_ROUTE25  = 'MAP_ROUTE25 '.freeze
    MAP_ONE_ISLAND_KINDLE_ROAD = 'MAP_ONE_ISLAND_KINDLE_ROAD '.freeze
    MAP_ONE_ISLAND_TREASURE_BEACH = 'MAP_ONE_ISLAND_TREASURE_BEACH '.freeze
    MAP_TWO_ISLAND_CAPE_BRINK = 'MAP_TWO_ISLAND_CAPE_BRINK '.freeze
    MAP_THREE_ISLAND_BOND_BRIDGE = 'MAP_THREE_ISLAND_BOND_BRIDGE '.freeze
    MAP_THREE_ISLAND_PORT = 'MAP_THREE_ISLAND_PORT '.freeze
    MAP_PROTOTYPE_SEVII_ISLE_6  = 'MAP_PROTOTYPE_SEVII_ISLE_6 '.freeze
    MAP_PROTOTYPE_SEVII_ISLE_7  = 'MAP_PROTOTYPE_SEVII_ISLE_7 '.freeze
    MAP_PROTOTYPE_SEVII_ISLE_8  = 'MAP_PROTOTYPE_SEVII_ISLE_8 '.freeze
    MAP_PROTOTYPE_SEVII_ISLE_9  = 'MAP_PROTOTYPE_SEVII_ISLE_9 '.freeze
    MAP_FIVE_ISLAND_RESORT_GORGEOUS  = 'MAP_FIVE_ISLAND_RESORT_GORGEOUS '.freeze
    MAP_FIVE_ISLAND_WATER_LABYRINTH  = 'MAP_FIVE_ISLAND_WATER_LABYRINTH '.freeze
    MAP_FIVE_ISLAND_MEADOW = 'MAP_FIVE_ISLAND_MEADOW '.freeze
    MAP_FIVE_ISLAND_MEMORIAL_PILLAR = 'MAP_FIVE_ISLAND_MEMORIAL_PILLAR '.freeze
    MAP_SIX_ISLAND_OUTCAST_ISLAND = 'MAP_SIX_ISLAND_OUTCAST_ISLAND '.freeze
    MAP_SIX_ISLAND_GREEN_PATH  = 'MAP_SIX_ISLAND_GREEN_PATH '.freeze
    MAP_SIX_ISLAND_WATER_PATH  = 'MAP_SIX_ISLAND_WATER_PATH '.freeze
    MAP_SIX_ISLAND_RUIN_VALLEY = 'MAP_SIX_ISLAND_RUIN_VALLEY '.freeze
    MAP_SEVEN_ISLAND_TRAINER_TOWER = 'MAP_SEVEN_ISLAND_TRAINER_TOWER '.freeze
    MAP_SEVEN_ISLAND_SEVAULT_CANYON_ENTRANCE = 'MAP_SEVEN_ISLAND_SEVAULT_CANYON_ENTRANCE'.freeze
    MAP_SEVEN_ISLAND_SEVAULT_CANYON = 'MAP_SEVEN_ISLAND_SEVAULT_CANYON '.freeze
    MAP_SEVEN_ISLAND_TANOBY_RUINS = 'MAP_SEVEN_ISLAND_TANOBY_RUINS '.freeze
    MAP_PALLET_TOWN_PLAYERS_HOUSE_1F  = 'MAP_PALLET_TOWN_PLAYERS_HOUSE_1F '.freeze
    MAP_PALLET_TOWN_PLAYERS_HOUSE_2F  = 'MAP_PALLET_TOWN_PLAYERS_HOUSE_2F '.freeze
    MAP_PALLET_TOWN_RIVALS_HOUSE = 'MAP_PALLET_TOWN_RIVALS_HOUSE '.freeze
    MAP_PALLET_TOWN_PROFESSOR_OAKS_LAB = 'MAP_PALLET_TOWN_PROFESSOR_OAKS_LAB'.freeze
    MAP_VIRIDIAN_CITY_HOUSE = 'MAP_VIRIDIAN_CITY_HOUSE '.freeze
    MAP_VIRIDIAN_CITY_GYM = 'MAP_VIRIDIAN_CITY_GYM '.freeze
    MAP_VIRIDIAN_CITY_SCHOOL = 'MAP_VIRIDIAN_CITY_SCHOOL '.freeze
    MAP_VIRIDIAN_CITY_MART = 'MAP_VIRIDIAN_CITY_MART '.freeze
    MAP_VIRIDIAN_CITY_POKEMON_CENTER_1F = 'MAP_VIRIDIAN_CITY_POKEMON_CENTER_1F'.freeze
    MAP_VIRIDIAN_CITY_POKEMON_CENTER_2F = 'MAP_VIRIDIAN_CITY_POKEMON_CENTER_2F'.freeze
    MAP_PEWTER_CITY_MUSEUM_1F  = 'MAP_PEWTER_CITY_MUSEUM_1F '.freeze
    MAP_PEWTER_CITY_MUSEUM_2F  = 'MAP_PEWTER_CITY_MUSEUM_2F '.freeze
    MAP_PEWTER_CITY_GYM = 'MAP_PEWTER_CITY_GYM '.freeze
    MAP_PEWTER_CITY_MART = 'MAP_PEWTER_CITY_MART '.freeze
    MAP_PEWTER_CITY_HOUSE1 = 'MAP_PEWTER_CITY_HOUSE1 '.freeze
    MAP_PEWTER_CITY_POKEMON_CENTER_1F = 'MAP_PEWTER_CITY_POKEMON_CENTER_1F'.freeze
    MAP_PEWTER_CITY_POKEMON_CENTER_2F = 'MAP_PEWTER_CITY_POKEMON_CENTER_2F'.freeze
    MAP_PEWTER_CITY_HOUSE2 = 'MAP_PEWTER_CITY_HOUSE2 '.freeze
    MAP_CERULEAN_CITY_HOUSE1  = 'MAP_CERULEAN_CITY_HOUSE1 '.freeze
    MAP_CERULEAN_CITY_HOUSE2  = 'MAP_CERULEAN_CITY_HOUSE2 '.freeze
    MAP_CERULEAN_CITY_HOUSE3  = 'MAP_CERULEAN_CITY_HOUSE3 '.freeze
    MAP_CERULEAN_CITY_POKEMON_CENTER_1F = 'MAP_CERULEAN_CITY_POKEMON_CENTER_1F'.freeze
    MAP_CERULEAN_CITY_POKEMON_CENTER_2F = 'MAP_CERULEAN_CITY_POKEMON_CENTER_2F'.freeze
    MAP_CERULEAN_CITY_GYM = 'MAP_CERULEAN_CITY_GYM '.freeze
    MAP_CERULEAN_CITY_BIKE_SHOP = 'MAP_CERULEAN_CITY_BIKE_SHOP '.freeze
    MAP_CERULEAN_CITY_MART = 'MAP_CERULEAN_CITY_MART '.freeze
    MAP_CERULEAN_CITY_HOUSE4  = 'MAP_CERULEAN_CITY_HOUSE4 '.freeze
    MAP_CERULEAN_CITY_HOUSE5  = 'MAP_CERULEAN_CITY_HOUSE5 '.freeze
    MAP_LAVENDER_TOWN_POKEMON_CENTER_1F  = 'MAP_LAVENDER_TOWN_POKEMON_CENTER_1F '.freeze
    MAP_LAVENDER_TOWN_POKEMON_CENTER_2F  = 'MAP_LAVENDER_TOWN_POKEMON_CENTER_2F '.freeze
    MAP_LAVENDER_TOWN_VOLUNTEER_POKEMON_HOUSE = 'MAP_LAVENDER_TOWN_VOLUNTEER_POKEMON_HOUSE'.freeze
    MAP_LAVENDER_TOWN_HOUSE1  = 'MAP_LAVENDER_TOWN_HOUSE1 '.freeze
    MAP_LAVENDER_TOWN_HOUSE2  = 'MAP_LAVENDER_TOWN_HOUSE2 '.freeze
    MAP_LAVENDER_TOWN_MART = 'MAP_LAVENDER_TOWN_MART '.freeze
    MAP_VERMILION_CITY_HOUSE1 = 'MAP_VERMILION_CITY_HOUSE1 '.freeze
    MAP_VERMILION_CITY_POKEMON_CENTER_1F = 'MAP_VERMILION_CITY_POKEMON_CENTER_1F'.freeze
    MAP_VERMILION_CITY_POKEMON_CENTER_2F = 'MAP_VERMILION_CITY_POKEMON_CENTER_2F'.freeze
    MAP_VERMILION_CITY_POKEMON_FAN_CLUB  = 'MAP_VERMILION_CITY_POKEMON_FAN_CLUB '.freeze
    MAP_VERMILION_CITY_HOUSE2 = 'MAP_VERMILION_CITY_HOUSE2 '.freeze
    MAP_VERMILION_CITY_MART = 'MAP_VERMILION_CITY_MART '.freeze
    MAP_VERMILION_CITY_GYM = 'MAP_VERMILION_CITY_GYM '.freeze
    MAP_VERMILION_CITY_HOUSE3 = 'MAP_VERMILION_CITY_HOUSE3 '.freeze
    MAP_CELADON_CITY_DEPARTMENT_STORE_1F  = 'MAP_CELADON_CITY_DEPARTMENT_STORE_1F '.freeze
    MAP_CELADON_CITY_DEPARTMENT_STORE_2F  = 'MAP_CELADON_CITY_DEPARTMENT_STORE_2F '.freeze
    MAP_CELADON_CITY_DEPARTMENT_STORE_3F  = 'MAP_CELADON_CITY_DEPARTMENT_STORE_3F '.freeze
    MAP_CELADON_CITY_DEPARTMENT_STORE_4F  = 'MAP_CELADON_CITY_DEPARTMENT_STORE_4F '.freeze
    MAP_CELADON_CITY_DEPARTMENT_STORE_5F  = 'MAP_CELADON_CITY_DEPARTMENT_STORE_5F '.freeze
    MAP_CELADON_CITY_DEPARTMENT_STORE_ROOF = 'MAP_CELADON_CITY_DEPARTMENT_STORE_ROOF '.freeze
    MAP_CELADON_CITY_DEPARTMENT_STORE_ELEVATOR = 'MAP_CELADON_CITY_DEPARTMENT_STORE_ELEVATOR'.freeze
    MAP_CELADON_CITY_CONDOMINIUMS_1F  = 'MAP_CELADON_CITY_CONDOMINIUMS_1F '.freeze
    MAP_CELADON_CITY_CONDOMINIUMS_2F  = 'MAP_CELADON_CITY_CONDOMINIUMS_2F '.freeze
    MAP_CELADON_CITY_CONDOMINIUMS_3F  = 'MAP_CELADON_CITY_CONDOMINIUMS_3F '.freeze
    MAP_CELADON_CITY_CONDOMINIUMS_ROOF = 'MAP_CELADON_CITY_CONDOMINIUMS_ROOF '.freeze
    MAP_CELADON_CITY_CONDOMINIUMS_ROOF_ROOM = 'MAP_CELADON_CITY_CONDOMINIUMS_ROOF_ROOM '.freeze
    MAP_CELADON_CITY_POKEMON_CENTER_1F  = 'MAP_CELADON_CITY_POKEMON_CENTER_1F '.freeze
    MAP_CELADON_CITY_POKEMON_CENTER_2F  = 'MAP_CELADON_CITY_POKEMON_CENTER_2F '.freeze
    MAP_CELADON_CITY_GAME_CORNER = 'MAP_CELADON_CITY_GAME_CORNER '.freeze
    MAP_CELADON_CITY_GAME_CORNER_PRIZE_ROOM = 'MAP_CELADON_CITY_GAME_CORNER_PRIZE_ROOM '.freeze
    MAP_CELADON_CITY_GYM = 'MAP_CELADON_CITY_GYM '.freeze
    MAP_CELADON_CITY_RESTAURANT = 'MAP_CELADON_CITY_RESTAURANT '.freeze
    MAP_CELADON_CITY_HOUSE1 = 'MAP_CELADON_CITY_HOUSE1 '.freeze
    MAP_CELADON_CITY_HOTEL = 'MAP_CELADON_CITY_HOTEL '.freeze
    MAP_FUCHSIA_CITY_SAFARI_ZONE_ENTRANCE = 'MAP_FUCHSIA_CITY_SAFARI_ZONE_ENTRANCE'.freeze
    MAP_FUCHSIA_CITY_MART = 'MAP_FUCHSIA_CITY_MART '.freeze
    MAP_FUCHSIA_CITY_SAFARI_ZONE_OFFICE = 'MAP_FUCHSIA_CITY_SAFARI_ZONE_OFFICE '.freeze
    MAP_FUCHSIA_CITY_GYM = 'MAP_FUCHSIA_CITY_GYM '.freeze
    MAP_FUCHSIA_CITY_HOUSE1 = 'MAP_FUCHSIA_CITY_HOUSE1 '.freeze
    MAP_FUCHSIA_CITY_POKEMON_CENTER_1F  = 'MAP_FUCHSIA_CITY_POKEMON_CENTER_1F '.freeze
    MAP_FUCHSIA_CITY_POKEMON_CENTER_2F  = 'MAP_FUCHSIA_CITY_POKEMON_CENTER_2F '.freeze
    MAP_FUCHSIA_CITY_WARDENS_HOUSE = 'MAP_FUCHSIA_CITY_WARDENS_HOUSE '.freeze
    MAP_FUCHSIA_CITY_HOUSE2  = 'MAP_FUCHSIA_CITY_HOUSE2 '.freeze
    MAP_FUCHSIA_CITY_HOUSE3  = 'MAP_FUCHSIA_CITY_HOUSE3 '.freeze
    MAP_CINNABAR_ISLAND_GYM  = 'MAP_CINNABAR_ISLAND_GYM '.freeze
    MAP_CINNABAR_ISLAND_POKEMON_LAB_ENTRANCE = 'MAP_CINNABAR_ISLAND_POKEMON_LAB_ENTRANCE '.freeze
    MAP_CINNABAR_ISLAND_POKEMON_LAB_LOUNGE = 'MAP_CINNABAR_ISLAND_POKEMON_LAB_LOUNGE '.freeze
    MAP_CINNABAR_ISLAND_POKEMON_LAB_RESEARCH_ROOM = 'MAP_CINNABAR_ISLAND_POKEMON_LAB_RESEARCH_ROOM '.freeze
    MAP_CINNABAR_ISLAND_POKEMON_LAB_EXPERIMENT_ROOM = 'MAP_CINNABAR_ISLAND_POKEMON_LAB_EXPERIMENT_ROOM'.freeze
    MAP_CINNABAR_ISLAND_POKEMON_CENTER_1F  = 'MAP_CINNABAR_ISLAND_POKEMON_CENTER_1F '.freeze
    MAP_CINNABAR_ISLAND_POKEMON_CENTER_2F  = 'MAP_CINNABAR_ISLAND_POKEMON_CENTER_2F '.freeze
    MAP_CINNABAR_ISLAND_MART = 'MAP_CINNABAR_ISLAND_MART '.freeze
    MAP_INDIGO_PLATEAU_POKEMON_CENTER_1F = 'MAP_INDIGO_PLATEAU_POKEMON_CENTER_1F'.freeze
    MAP_INDIGO_PLATEAU_POKEMON_CENTER_2F = 'MAP_INDIGO_PLATEAU_POKEMON_CENTER_2F'.freeze
    MAP_SAFFRON_CITY_COPYCATS_HOUSE_1F  = 'MAP_SAFFRON_CITY_COPYCATS_HOUSE_1F '.freeze
    MAP_SAFFRON_CITY_COPYCATS_HOUSE_2F  = 'MAP_SAFFRON_CITY_COPYCATS_HOUSE_2F '.freeze
    MAP_SAFFRON_CITY_DOJO = 'MAP_SAFFRON_CITY_DOJO '.freeze
    MAP_SAFFRON_CITY_GYM = 'MAP_SAFFRON_CITY_GYM '.freeze
    MAP_SAFFRON_CITY_HOUSE = 'MAP_SAFFRON_CITY_HOUSE '.freeze
    MAP_SAFFRON_CITY_MART = 'MAP_SAFFRON_CITY_MART '.freeze
    MAP_SAFFRON_CITY_POKEMON_CENTER_1F  = 'MAP_SAFFRON_CITY_POKEMON_CENTER_1F '.freeze
    MAP_SAFFRON_CITY_POKEMON_CENTER_2F  = 'MAP_SAFFRON_CITY_POKEMON_CENTER_2F '.freeze
    MAP_SAFFRON_CITY_MR_PSYCHICS_HOUSE  = 'MAP_SAFFRON_CITY_MR_PSYCHICS_HOUSE '.freeze
    MAP_SAFFRON_CITY_POKEMON_TRAINER_FAN_CLUB = 'MAP_SAFFRON_CITY_POKEMON_TRAINER_FAN_CLUB'.freeze
    MAP_ROUTE2_VIRIDIAN_FOREST_SOUTH_ENTRANCE = 'MAP_ROUTE2_VIRIDIAN_FOREST_SOUTH_ENTRANCE'.freeze
    MAP_ROUTE2_HOUSE = 'MAP_ROUTE2_HOUSE '.freeze
    MAP_ROUTE2_EAST_BUILDING = 'MAP_ROUTE2_EAST_BUILDING '.freeze
    MAP_ROUTE2_VIRIDIAN_FOREST_NORTH_ENTRANCE = 'MAP_ROUTE2_VIRIDIAN_FOREST_NORTH_ENTRANCE'.freeze
    MAP_ROUTE4_POKEMON_CENTER_1F = 'MAP_ROUTE4_POKEMON_CENTER_1F'.freeze
    MAP_ROUTE4_POKEMON_CENTER_2F = 'MAP_ROUTE4_POKEMON_CENTER_2F'.freeze
    MAP_ROUTE5_POKEMON_DAY_CARE = 'MAP_ROUTE5_POKEMON_DAY_CARE'.freeze
    MAP_ROUTE5_SOUTH_ENTRANCE = 'MAP_ROUTE5_SOUTH_ENTRANCE '.freeze
    MAP_ROUTE6_NORTH_ENTRANCE = 'MAP_ROUTE6_NORTH_ENTRANCE'.freeze
    MAP_ROUTE6_UNUSED_HOUSE  = 'MAP_ROUTE6_UNUSED_HOUSE '.freeze
    MAP_ROUTE7_EAST_ENTRANCE = 'MAP_ROUTE7_EAST_ENTRANCE'.freeze
    MAP_ROUTE8_WEST_ENTRANCE = 'MAP_ROUTE8_WEST_ENTRANCE'.freeze
    MAP_ROUTE10_POKEMON_CENTER_1F = 'MAP_ROUTE10_POKEMON_CENTER_1F'.freeze
    MAP_ROUTE10_POKEMON_CENTER_2F = 'MAP_ROUTE10_POKEMON_CENTER_2F'.freeze
    MAP_ROUTE11_EAST_ENTRANCE_1F = 'MAP_ROUTE11_EAST_ENTRANCE_1F'.freeze
    MAP_ROUTE11_EAST_ENTRANCE_2F = 'MAP_ROUTE11_EAST_ENTRANCE_2F'.freeze
    MAP_ROUTE12_NORTH_ENTRANCE_1F = 'MAP_ROUTE12_NORTH_ENTRANCE_1F'.freeze
    MAP_ROUTE12_NORTH_ENTRANCE_2F = 'MAP_ROUTE12_NORTH_ENTRANCE_2F'.freeze
    MAP_ROUTE12_FISHING_HOUSE = 'MAP_ROUTE12_FISHING_HOUSE '.freeze
    MAP_ROUTE15_WEST_ENTRANCE_1F = 'MAP_ROUTE15_WEST_ENTRANCE_1F'.freeze
    MAP_ROUTE15_WEST_ENTRANCE_2F = 'MAP_ROUTE15_WEST_ENTRANCE_2F'.freeze
    MAP_ROUTE16_HOUSE = 'MAP_ROUTE16_HOUSE '.freeze
    MAP_ROUTE16_NORTH_ENTRANCE_1F = 'MAP_ROUTE16_NORTH_ENTRANCE_1F'.freeze
    MAP_ROUTE16_NORTH_ENTRANCE_2F = 'MAP_ROUTE16_NORTH_ENTRANCE_2F'.freeze
    MAP_ROUTE18_EAST_ENTRANCE_1F = 'MAP_ROUTE18_EAST_ENTRANCE_1F'.freeze
    MAP_ROUTE18_EAST_ENTRANCE_2F = 'MAP_ROUTE18_EAST_ENTRANCE_2F'.freeze
    MAP_ROUTE19_UNUSED_HOUSE = 'MAP_ROUTE19_UNUSED_HOUSE'.freeze
    MAP_ROUTE22_NORTH_ENTRANCE = 'MAP_ROUTE22_NORTH_ENTRANCE'.freeze
    MAP_ROUTE23_UNUSED_HOUSE = 'MAP_ROUTE23_UNUSED_HOUSE'.freeze
    MAP_ROUTE25_SEA_COTTAGE = 'MAP_ROUTE25_SEA_COTTAGE'.freeze
    MAP_SEVEN_ISLAND_HOUSE_ROOM1  = 'MAP_SEVEN_ISLAND_HOUSE_ROOM1 '.freeze
    MAP_SEVEN_ISLAND_HOUSE_ROOM2  = 'MAP_SEVEN_ISLAND_HOUSE_ROOM2 '.freeze
    MAP_SEVEN_ISLAND_MART = 'MAP_SEVEN_ISLAND_MART '.freeze
    MAP_SEVEN_ISLAND_POKEMON_CENTER_1F = 'MAP_SEVEN_ISLAND_POKEMON_CENTER_1F'.freeze
    MAP_SEVEN_ISLAND_POKEMON_CENTER_2F = 'MAP_SEVEN_ISLAND_POKEMON_CENTER_2F'.freeze
    MAP_SEVEN_ISLAND_UNUSED_HOUSE = 'MAP_SEVEN_ISLAND_UNUSED_HOUSE '.freeze
    MAP_SEVEN_ISLAND_HARBOR = 'MAP_SEVEN_ISLAND_HARBOR '.freeze
    MAP_ONE_ISLAND_POKEMON_CENTER_1F = 'MAP_ONE_ISLAND_POKEMON_CENTER_1F'.freeze
    MAP_ONE_ISLAND_POKEMON_CENTER_2F = 'MAP_ONE_ISLAND_POKEMON_CENTER_2F'.freeze
    MAP_ONE_ISLAND_HOUSE1  = 'MAP_ONE_ISLAND_HOUSE1 '.freeze
    MAP_ONE_ISLAND_HOUSE2  = 'MAP_ONE_ISLAND_HOUSE2 '.freeze
    MAP_ONE_ISLAND_HARBOR  = 'MAP_ONE_ISLAND_HARBOR '.freeze
    MAP_TWO_ISLAND_JOYFUL_GAME_CORNER = 'MAP_TWO_ISLAND_JOYFUL_GAME_CORNER'.freeze
    MAP_TWO_ISLAND_HOUSE = 'MAP_TWO_ISLAND_HOUSE '.freeze
    MAP_TWO_ISLAND_POKEMON_CENTER_1F  = 'MAP_TWO_ISLAND_POKEMON_CENTER_1F '.freeze
    MAP_TWO_ISLAND_POKEMON_CENTER_2F  = 'MAP_TWO_ISLAND_POKEMON_CENTER_2F '.freeze
    MAP_TWO_ISLAND_HARBOR = 'MAP_TWO_ISLAND_HARBOR '.freeze
    MAP_THREE_ISLAND_HOUSE1 = 'MAP_THREE_ISLAND_HOUSE1 '.freeze
    MAP_THREE_ISLAND_POKEMON_CENTER_1F = 'MAP_THREE_ISLAND_POKEMON_CENTER_1F'.freeze
    MAP_THREE_ISLAND_POKEMON_CENTER_2F = 'MAP_THREE_ISLAND_POKEMON_CENTER_2F'.freeze
    MAP_THREE_ISLAND_MART = 'MAP_THREE_ISLAND_MART '.freeze
    MAP_THREE_ISLAND_HOUSE2  = 'MAP_THREE_ISLAND_HOUSE2 '.freeze
    MAP_THREE_ISLAND_HOUSE3  = 'MAP_THREE_ISLAND_HOUSE3 '.freeze
    MAP_THREE_ISLAND_HOUSE4  = 'MAP_THREE_ISLAND_HOUSE4 '.freeze
    MAP_THREE_ISLAND_HOUSE5  = 'MAP_THREE_ISLAND_HOUSE5 '.freeze
    MAP_FOUR_ISLAND_POKEMON_DAY_CARE  = 'MAP_FOUR_ISLAND_POKEMON_DAY_CARE '.freeze
    MAP_FOUR_ISLAND_POKEMON_CENTER_1F = 'MAP_FOUR_ISLAND_POKEMON_CENTER_1F'.freeze
    MAP_FOUR_ISLAND_POKEMON_CENTER_2F = 'MAP_FOUR_ISLAND_POKEMON_CENTER_2F'.freeze
    MAP_FOUR_ISLAND_HOUSE1 = 'MAP_FOUR_ISLAND_HOUSE1 '.freeze
    MAP_FOUR_ISLAND_LORELEIS_HOUSE = 'MAP_FOUR_ISLAND_LORELEIS_HOUSE '.freeze
    MAP_FOUR_ISLAND_HARBOR  = 'MAP_FOUR_ISLAND_HARBOR '.freeze
    MAP_FOUR_ISLAND_HOUSE2  = 'MAP_FOUR_ISLAND_HOUSE2 '.freeze
    MAP_FOUR_ISLAND_MART = 'MAP_FOUR_ISLAND_MART '.freeze
    MAP_FIVE_ISLAND_POKEMON_CENTER_1F = 'MAP_FIVE_ISLAND_POKEMON_CENTER_1F'.freeze
    MAP_FIVE_ISLAND_POKEMON_CENTER_2F = 'MAP_FIVE_ISLAND_POKEMON_CENTER_2F'.freeze
    MAP_FIVE_ISLAND_HARBOR  = 'MAP_FIVE_ISLAND_HARBOR '.freeze
    MAP_FIVE_ISLAND_HOUSE1  = 'MAP_FIVE_ISLAND_HOUSE1 '.freeze
    MAP_FIVE_ISLAND_HOUSE2  = 'MAP_FIVE_ISLAND_HOUSE2 '.freeze
    MAP_SIX_ISLAND_POKEMON_CENTER_1F = 'MAP_SIX_ISLAND_POKEMON_CENTER_1F'.freeze
    MAP_SIX_ISLAND_POKEMON_CENTER_2F = 'MAP_SIX_ISLAND_POKEMON_CENTER_2F'.freeze
    MAP_SIX_ISLAND_HARBOR = 'MAP_SIX_ISLAND_HARBOR '.freeze
    MAP_SIX_ISLAND_HOUSE = 'MAP_SIX_ISLAND_HOUSE '.freeze
    MAP_SIX_ISLAND_MART = 'MAP_SIX_ISLAND_MART '.freeze
    MAP_THREE_ISLAND_HARBOR = 'MAP_THREE_ISLAND_HARBOR'.freeze
    MAP_FIVE_ISLAND_RESORT_GORGEOUS_HOUSE = 'MAP_FIVE_ISLAND_RESORT_GORGEOUS_HOUSE'.freeze
    MAP_TWO_ISLAND_CAPE_BRINK_HOUSE = 'MAP_TWO_ISLAND_CAPE_BRINK_HOUSE'.freeze
    MAP_SIX_ISLAND_WATER_PATH_HOUSE1 = 'MAP_SIX_ISLAND_WATER_PATH_HOUSE1'.freeze
    MAP_SIX_ISLAND_WATER_PATH_HOUSE2 = 'MAP_SIX_ISLAND_WATER_PATH_HOUSE2'.freeze
    MAP_SEVEN_ISLAND_SEVAULT_CANYON_HOUSE = 'MAP_SEVEN_ISLAND_SEVAULT_CANYON_HOUSE'.freeze
    MAP_GROUP = {
      group0_num0: MAP_BATTLE_COLOSSEUM_2P,
      group0_num1: MAP_TRADE_CENTER,
      group0_num2: MAP_RECORD_CORNER,
      group0_num3: MAP_BATTLE_COLOSSEUM_4P,
      group0_num4: MAP_UNION_ROOM,
      group1_num0: MAP_VIRIDIAN_FOREST,
      group1_num1: MAP_MT_MOON_1F,
      group1_num2: MAP_MT_MOON_B1F,
      group1_num3: MAP_MT_MOON_B2F,
      group1_num4: MAP_SSANNE_EXTERIOR,
      group1_num5: MAP_SSANNE_1F_CORRIDOR,
      group1_num6: MAP_SSANNE_2F_CORRIDOR,
      group1_num7: MAP_SSANNE_3F_CORRIDOR,
      group1_num8: MAP_SSANNE_B1F_CORRIDOR,
      group1_num9: MAP_SSANNE_DECK,
      group1_num10: MAP_SSANNE_KITCHEN,
      group1_num11: MAP_SSANNE_CAPTAINS_OFFICE,
      group1_num12: MAP_SSANNE_1F_ROOM1,
      group1_num13: MAP_SSANNE_1F_ROOM2,
      group1_num14: MAP_SSANNE_1F_ROOM3,
      group1_num15: MAP_SSANNE_1F_ROOM4,
      group1_num16: MAP_SSANNE_1F_ROOM5,
      group1_num17: MAP_SSANNE_1F_ROOM7,
      group1_num18: MAP_SSANNE_2F_ROOM1,
      group1_num19: MAP_SSANNE_2F_ROOM2,
      group1_num20: MAP_SSANNE_2F_ROOM3,
      group1_num21: MAP_SSANNE_2F_ROOM4,
      group1_num22: MAP_SSANNE_2F_ROOM5,
      group1_num23: MAP_SSANNE_2F_ROOM6,
      group1_num24: MAP_SSANNE_B1F_ROOM1,
      group1_num25: MAP_SSANNE_B1F_ROOM2,
      group1_num26: MAP_SSANNE_B1F_ROOM3,
      group1_num27: MAP_SSANNE_B1F_ROOM4,
      group1_num28: MAP_SSANNE_B1F_ROOM5,
      group1_num29: MAP_SSANNE_1F_ROOM6,
      group1_num30: MAP_UNDERGROUND_PATH_NORTH_ENTRANCE,
      group1_num31: MAP_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL,
      group1_num32: MAP_UNDERGROUND_PATH_SOUTH_ENTRANCE,
      group1_num33: MAP_UNDERGROUND_PATH_WEST_ENTRANCE,
      group1_num34: MAP_UNDERGROUND_PATH_EAST_WEST_TUNNEL,
      group1_num35: MAP_UNDERGROUND_PATH_EAST_ENTRANCE,
      group1_num36: MAP_DIGLETTS_CAVE_NORTH_ENTRANCE,
      group1_num37: MAP_DIGLETTS_CAVE_B1F,
      group1_num38: MAP_DIGLETTS_CAVE_SOUTH_ENTRANCE,
      group1_num39: MAP_VICTORY_ROAD_1F,
      group1_num40: MAP_VICTORY_ROAD_2F,
      group1_num41: MAP_VICTORY_ROAD_3F,
      group1_num42: MAP_ROCKET_HIDEOUT_B1F,
      group1_num43: MAP_ROCKET_HIDEOUT_B2F,
      group1_num44: MAP_ROCKET_HIDEOUT_B3F,
      group1_num45: MAP_ROCKET_HIDEOUT_B4F,
      group1_num46: MAP_ROCKET_HIDEOUT_ELEVATOR,
      group1_num47: MAP_SILPH_CO_1F,
      group1_num48: MAP_SILPH_CO_2F,
      group1_num49: MAP_SILPH_CO_3F,
      group1_num50: MAP_SILPH_CO_4F,
      group1_num51: MAP_SILPH_CO_5F,
      group1_num52: MAP_SILPH_CO_6F,
      group1_num53: MAP_SILPH_CO_7F,
      group1_num54: MAP_SILPH_CO_8F,
      group1_num55: MAP_SILPH_CO_9F,
      group1_num56: MAP_SILPH_CO_10F,
      group1_num57: MAP_SILPH_CO_11F,
      group1_num58: MAP_SILPH_CO_ELEVATOR,
      group1_num59: MAP_POKEMON_MANSION_1F,
      group1_num60: MAP_POKEMON_MANSION_2F,
      group1_num61: MAP_POKEMON_MANSION_3F,
      group1_num62: MAP_POKEMON_MANSION_B1F,
      group1_num63: MAP_SAFARI_ZONE_CENTER,
      group1_num64: MAP_SAFARI_ZONE_EAST,
      group1_num65: MAP_SAFARI_ZONE_NORTH,
      group1_num66: MAP_SAFARI_ZONE_WEST,
      group1_num67: MAP_SAFARI_ZONE_CENTER_REST_HOUSE,
      group1_num68: MAP_SAFARI_ZONE_EAST_REST_HOUSE,
      group1_num69: MAP_SAFARI_ZONE_NORTH_REST_HOUSE,
      group1_num70: MAP_SAFARI_ZONE_WEST_REST_HOUSE,
      group1_num71: MAP_SAFARI_ZONE_SECRET_HOUSE,
      group1_num72: MAP_CERULEAN_CAVE_1F,
      group1_num73: MAP_CERULEAN_CAVE_2F,
      group1_num74: MAP_CERULEAN_CAVE_B1F,
      group1_num75: MAP_POKEMON_LEAGUE_LORELEIS_ROOM,
      group1_num76: MAP_POKEMON_LEAGUE_BRUNOS_ROOM,
      group1_num77: MAP_POKEMON_LEAGUE_AGATHAS_ROOM,
      group1_num78: MAP_POKEMON_LEAGUE_LANCES_ROOM,
      group1_num79: MAP_POKEMON_LEAGUE_CHAMPIONS_ROOM,
      group1_num80: MAP_POKEMON_LEAGUE_HALL_OF_FAME,
      group1_num81: MAP_ROCK_TUNNEL_1F,
      group1_num82: MAP_ROCK_TUNNEL_B1F,
      group1_num83: MAP_SEAFOAM_ISLANDS_1F,
      group1_num84: MAP_SEAFOAM_ISLANDS_B1F,
      group1_num85: MAP_SEAFOAM_ISLANDS_B2F,
      group1_num86: MAP_SEAFOAM_ISLANDS_B3F,
      group1_num87: MAP_SEAFOAM_ISLANDS_B4F,
      group1_num88: MAP_POKEMON_TOWER_1F,
      group1_num89: MAP_POKEMON_TOWER_2F,
      group1_num90: MAP_POKEMON_TOWER_3F,
      group1_num91: MAP_POKEMON_TOWER_4F,
      group1_num92: MAP_POKEMON_TOWER_5F,
      group1_num93: MAP_POKEMON_TOWER_6F,
      group1_num94: MAP_POKEMON_TOWER_7F,
      group1_num95: MAP_POWER_PLANT,
      group1_num96: MAP_MT_EMBER_RUBY_PATH_B4F,
      group1_num97: MAP_MT_EMBER_EXTERIOR,
      group1_num98: MAP_MT_EMBER_SUMMIT_PATH_1F,
      group1_num99: MAP_MT_EMBER_SUMMIT_PATH_2F,
      group1_num100: MAP_MT_EMBER_SUMMIT_PATH_3F,
      group1_num101: MAP_MT_EMBER_SUMMIT,
      group1_num102: MAP_MT_EMBER_RUBY_PATH_B5F,
      group1_num103: MAP_MT_EMBER_RUBY_PATH_1F,
      group1_num104: MAP_MT_EMBER_RUBY_PATH_B1F,
      group1_num105: MAP_MT_EMBER_RUBY_PATH_B2F,
      group1_num106: MAP_MT_EMBER_RUBY_PATH_B3F,
      group1_num107: MAP_MT_EMBER_RUBY_PATH_B1F_STAIRS,
      group1_num108: MAP_MT_EMBER_RUBY_PATH_B2F_STAIRS,
      group1_num109: MAP_THREE_ISLAND_BERRY_FOREST,
      group1_num110: MAP_FOUR_ISLAND_ICEFALL_CAVE_ENTRANCE,
      group1_num111: MAP_FOUR_ISLAND_ICEFALL_CAVE_1F,
      group1_num112: MAP_FOUR_ISLAND_ICEFALL_CAVE_B1F,
      group1_num113: MAP_FOUR_ISLAND_ICEFALL_CAVE_BACK,
      group1_num114: MAP_FIVE_ISLAND_ROCKET_WAREHOUSE,
      group1_num115: MAP_SIX_ISLAND_DOTTED_HOLE_1F,
      group1_num116: MAP_SIX_ISLAND_DOTTED_HOLE_B1F,
      group1_num117: MAP_SIX_ISLAND_DOTTED_HOLE_B2F,
      group1_num118: MAP_SIX_ISLAND_DOTTED_HOLE_B3F,
      group1_num119: MAP_SIX_ISLAND_DOTTED_HOLE_B4F,
      group1_num120: MAP_SIX_ISLAND_DOTTED_HOLE_SAPPHIRE_ROOM,
      group1_num121: MAP_SIX_ISLAND_PATTERN_BUSH,
      group1_num122: MAP_SIX_ISLAND_ALTERING_CAVE,
      group2_num0: MAP_NAVEL_ROCK_EXTERIOR,
      group2_num1: MAP_TRAINER_TOWER_1F,
      group2_num2: MAP_TRAINER_TOWER_2F,
      group2_num3: MAP_TRAINER_TOWER_3F,
      group2_num4: MAP_TRAINER_TOWER_4F,
      group2_num5: MAP_TRAINER_TOWER_5F,
      group2_num6: MAP_TRAINER_TOWER_6F,
      group2_num7: MAP_TRAINER_TOWER_7F,
      group2_num8: MAP_TRAINER_TOWER_8F,
      group2_num9: MAP_TRAINER_TOWER_ROOF,
      group2_num10: MAP_TRAINER_TOWER_LOBBY,
      group2_num11: MAP_TRAINER_TOWER_ELEVATOR,
      group2_num12: MAP_FIVE_ISLAND_LOST_CAVE_ENTRANCE,
      group2_num13: MAP_FIVE_ISLAND_LOST_CAVE_ROOM1,
      group2_num14: MAP_FIVE_ISLAND_LOST_CAVE_ROOM2,
      group2_num15: MAP_FIVE_ISLAND_LOST_CAVE_ROOM3,
      group2_num16: MAP_FIVE_ISLAND_LOST_CAVE_ROOM4,
      group2_num17: MAP_FIVE_ISLAND_LOST_CAVE_ROOM5,
      group2_num18: MAP_FIVE_ISLAND_LOST_CAVE_ROOM6,
      group2_num19: MAP_FIVE_ISLAND_LOST_CAVE_ROOM7,
      group2_num20: MAP_FIVE_ISLAND_LOST_CAVE_ROOM8,
      group2_num21: MAP_FIVE_ISLAND_LOST_CAVE_ROOM9,
      group2_num22: MAP_FIVE_ISLAND_LOST_CAVE_ROOM10,
      group2_num23: MAP_FIVE_ISLAND_LOST_CAVE_ROOM11,
      group2_num24: MAP_FIVE_ISLAND_LOST_CAVE_ROOM12,
      group2_num25: MAP_FIVE_ISLAND_LOST_CAVE_ROOM13,
      group2_num26: MAP_FIVE_ISLAND_LOST_CAVE_ROOM14,
      group2_num27: MAP_SEVEN_ISLAND_TANOBY_RUINS_MONEAN_CHAMBER,
      group2_num28: MAP_SEVEN_ISLAND_TANOBY_RUINS_LIPTOO_CHAMBER,
      group2_num29: MAP_SEVEN_ISLAND_TANOBY_RUINS_WEEPTH_CHAMBER,
      group2_num30: MAP_SEVEN_ISLAND_TANOBY_RUINS_DILFORD_CHAMBER,
      group2_num31: MAP_SEVEN_ISLAND_TANOBY_RUINS_SCUFIB_CHAMBER,
      group2_num32: MAP_SEVEN_ISLAND_TANOBY_RUINS_RIXY_CHAMBER,
      group2_num33: MAP_SEVEN_ISLAND_TANOBY_RUINS_VIAPOIS_CHAMBER,
      group2_num34: MAP_THREE_ISLAND_DUNSPARCE_TUNNEL,
      group2_num35: MAP_SEVEN_ISLAND_SEVAULT_CANYON_TANOBY_KEY,
      group2_num36: MAP_NAVEL_ROCK_1F,
      group2_num37: MAP_NAVEL_ROCK_SUMMIT,
      group2_num38: MAP_NAVEL_ROCK_BASE,
      group2_num39: MAP_NAVEL_ROCK_SUMMIT_PATH_2F,
      group2_num40: MAP_NAVEL_ROCK_SUMMIT_PATH_3F,
      group2_num41: MAP_NAVEL_ROCK_SUMMIT_PATH_4F,
      group2_num42: MAP_NAVEL_ROCK_SUMMIT_PATH_5F,
      group2_num43: MAP_NAVEL_ROCK_BASE_PATH_B1F,
      group2_num44: MAP_NAVEL_ROCK_BASE_PATH_B2F,
      group2_num45: MAP_NAVEL_ROCK_BASE_PATH_B3F,
      group2_num46: MAP_NAVEL_ROCK_BASE_PATH_B4F,
      group2_num47: MAP_NAVEL_ROCK_BASE_PATH_B5F,
      group2_num48: MAP_NAVEL_ROCK_BASE_PATH_B6F,
      group2_num49: MAP_NAVEL_ROCK_BASE_PATH_B7F,
      group2_num50: MAP_NAVEL_ROCK_BASE_PATH_B8F,
      group2_num51: MAP_NAVEL_ROCK_BASE_PATH_B9F,
      group2_num52: MAP_NAVEL_ROCK_BASE_PATH_B10F,
      group2_num53: MAP_NAVEL_ROCK_BASE_PATH_B11F,
      group2_num54: MAP_NAVEL_ROCK_B1F,
      group2_num55: MAP_NAVEL_ROCK_FORK,
      group2_num56: MAP_BIRTH_ISLAND_EXTERIOR,
      group2_num57: MAP_ONE_ISLAND_KINDLE_ROAD_EMBER_SPA,
      group2_num58: MAP_BIRTH_ISLAND_HARBOR,
      group2_num59: MAP_NAVEL_ROCK_HARBOR,
      group3_num0: MAP_PALLET_TOWN,
      group3_num1: MAP_VIRIDIAN_CITY,
      group3_num2: MAP_PEWTER_CITY,
      group3_num3: MAP_CERULEAN_CITY,
      group3_num4: MAP_LAVENDER_TOWN,
      group3_num5: MAP_VERMILION_CITY,
      group3_num6: MAP_CELADON_CITY,
      group3_num7: MAP_FUCHSIA_CITY,
      group3_num8: MAP_CINNABAR_ISLAND,
      group3_num9: MAP_INDIGO_PLATEAU_EXTERIOR,
      group3_num10: MAP_SAFFRON_CITY,
      group3_num11: MAP_SAFFRON_CITY_CONNECTION,
      group3_num12: MAP_ONE_ISLAND,
      group3_num13: MAP_TWO_ISLAND,
      group3_num14: MAP_THREE_ISLAND,
      group3_num15: MAP_FOUR_ISLAND,
      group3_num16: MAP_FIVE_ISLAND,
      group3_num17: MAP_SEVEN_ISLAND,
      group3_num18: MAP_SIX_ISLAND,
      group3_num19: MAP_ROUTE1,
      group3_num20: MAP_ROUTE2,
      group3_num21: MAP_ROUTE3,
      group3_num22: MAP_ROUTE4,
      group3_num23: MAP_ROUTE5,
      group3_num24: MAP_ROUTE6,
      group3_num25: MAP_ROUTE7,
      group3_num26: MAP_ROUTE8,
      group3_num27: MAP_ROUTE9,
      group3_num28: MAP_ROUTE10,
      group3_num29: MAP_ROUTE11,
      group3_num30: MAP_ROUTE12,
      group3_num31: MAP_ROUTE13,
      group3_num32: MAP_ROUTE14,
      group3_num33: MAP_ROUTE15,
      group3_num34: MAP_ROUTE16,
      group3_num35: MAP_ROUTE17,
      group3_num36: MAP_ROUTE18,
      group3_num37: MAP_ROUTE19,
      group3_num38: MAP_ROUTE20,
      group3_num39: MAP_ROUTE21_NORTH,
      group3_num40: MAP_ROUTE21_SOUTH,
      group3_num41: MAP_ROUTE22,
      group3_num42: MAP_ROUTE23,
      group3_num43: MAP_ROUTE24,
      group3_num44: MAP_ROUTE25,
      group3_num45: MAP_ONE_ISLAND_KINDLE_ROAD,
      group3_num46: MAP_ONE_ISLAND_TREASURE_BEACH,
      group3_num47: MAP_TWO_ISLAND_CAPE_BRINK,
      group3_num48: MAP_THREE_ISLAND_BOND_BRIDGE,
      group3_num49: MAP_THREE_ISLAND_PORT,
      group3_num50: MAP_PROTOTYPE_SEVII_ISLE_6,
      group3_num51: MAP_PROTOTYPE_SEVII_ISLE_7,
      group3_num52: MAP_PROTOTYPE_SEVII_ISLE_8,
      group3_num53: MAP_PROTOTYPE_SEVII_ISLE_9,
      group3_num54: MAP_FIVE_ISLAND_RESORT_GORGEOUS,
      group3_num55: MAP_FIVE_ISLAND_WATER_LABYRINTH,
      group3_num56: MAP_FIVE_ISLAND_MEADOW,
      group3_num57: MAP_FIVE_ISLAND_MEMORIAL_PILLAR,
      group3_num58: MAP_SIX_ISLAND_OUTCAST_ISLAND,
      group3_num59: MAP_SIX_ISLAND_GREEN_PATH,
      group3_num60: MAP_SIX_ISLAND_WATER_PATH,
      group3_num61: MAP_SIX_ISLAND_RUIN_VALLEY,
      group3_num62: MAP_SEVEN_ISLAND_TRAINER_TOWER,
      group3_num63: MAP_SEVEN_ISLAND_SEVAULT_CANYON_ENTRANCE,
      group3_num64: MAP_SEVEN_ISLAND_SEVAULT_CANYON,
      group3_num65: MAP_SEVEN_ISLAND_TANOBY_RUINS,
      group4_num0: MAP_PALLET_TOWN_PLAYERS_HOUSE_1F,
      group4_num1: MAP_PALLET_TOWN_PLAYERS_HOUSE_2F,
      group4_num2: MAP_PALLET_TOWN_RIVALS_HOUSE,
      group4_num3: MAP_PALLET_TOWN_PROFESSOR_OAKS_LAB,
      group5_num0: MAP_VIRIDIAN_CITY_HOUSE,
      group5_num1: MAP_VIRIDIAN_CITY_GYM,
      group5_num2: MAP_VIRIDIAN_CITY_SCHOOL,
      group5_num3: MAP_VIRIDIAN_CITY_MART,
      group5_num4: MAP_VIRIDIAN_CITY_POKEMON_CENTER_1F,
      group5_num5: MAP_VIRIDIAN_CITY_POKEMON_CENTER_2F,
      group6_num0: MAP_PEWTER_CITY_MUSEUM_1F,
      group6_num1: MAP_PEWTER_CITY_MUSEUM_2F,
      group6_num2: MAP_PEWTER_CITY_GYM,
      group6_num3: MAP_PEWTER_CITY_MART,
      group6_num4: MAP_PEWTER_CITY_HOUSE1,
      group6_num5: MAP_PEWTER_CITY_POKEMON_CENTER_1F,
      group6_num6: MAP_PEWTER_CITY_POKEMON_CENTER_2F,
      group6_num7: MAP_PEWTER_CITY_HOUSE2,
      group7_num0: MAP_CERULEAN_CITY_HOUSE1,
      group7_num1: MAP_CERULEAN_CITY_HOUSE2,
      group7_num2: MAP_CERULEAN_CITY_HOUSE3,
      group7_num3: MAP_CERULEAN_CITY_POKEMON_CENTER_1F,
      group7_num4: MAP_CERULEAN_CITY_POKEMON_CENTER_2F,
      group7_num5: MAP_CERULEAN_CITY_GYM,
      group7_num6: MAP_CERULEAN_CITY_BIKE_SHOP,
      group7_num7: MAP_CERULEAN_CITY_MART,
      group7_num8: MAP_CERULEAN_CITY_HOUSE4,
      group7_num9: MAP_CERULEAN_CITY_HOUSE5,
      group8_num0: MAP_LAVENDER_TOWN_POKEMON_CENTER_1F,
      group8_num1: MAP_LAVENDER_TOWN_POKEMON_CENTER_2F,
      group8_num2: MAP_LAVENDER_TOWN_VOLUNTEER_POKEMON_HOUSE,
      group8_num3: MAP_LAVENDER_TOWN_HOUSE1,
      group8_num4: MAP_LAVENDER_TOWN_HOUSE2,
      group8_num5: MAP_LAVENDER_TOWN_MART,
      group9_num0: MAP_VERMILION_CITY_HOUSE1,
      group9_num1: MAP_VERMILION_CITY_POKEMON_CENTER_1F,
      group9_num2: MAP_VERMILION_CITY_POKEMON_CENTER_2F,
      group9_num3: MAP_VERMILION_CITY_POKEMON_FAN_CLUB,
      group9_num4: MAP_VERMILION_CITY_HOUSE2,
      group9_num5: MAP_VERMILION_CITY_MART,
      group9_num6: MAP_VERMILION_CITY_GYM,
      group9_num7: MAP_VERMILION_CITY_HOUSE3,
      group10_num0: MAP_CELADON_CITY_DEPARTMENT_STORE_1F,
      group10_num1: MAP_CELADON_CITY_DEPARTMENT_STORE_2F,
      group10_num2: MAP_CELADON_CITY_DEPARTMENT_STORE_3F,
      group10_num3: MAP_CELADON_CITY_DEPARTMENT_STORE_4F,
      group10_num4: MAP_CELADON_CITY_DEPARTMENT_STORE_5F,
      group10_num5: MAP_CELADON_CITY_DEPARTMENT_STORE_ROOF,
      group10_num6: MAP_CELADON_CITY_DEPARTMENT_STORE_ELEVATOR,
      group10_num7: MAP_CELADON_CITY_CONDOMINIUMS_1F,
      group10_num8: MAP_CELADON_CITY_CONDOMINIUMS_2F,
      group10_num9: MAP_CELADON_CITY_CONDOMINIUMS_3F,
      group10_num10: MAP_CELADON_CITY_CONDOMINIUMS_ROOF,
      group10_num11: MAP_CELADON_CITY_CONDOMINIUMS_ROOF_ROOM,
      group10_num12: MAP_CELADON_CITY_POKEMON_CENTER_1F,
      group10_num13: MAP_CELADON_CITY_POKEMON_CENTER_2F,
      group10_num14: MAP_CELADON_CITY_GAME_CORNER,
      group10_num15: MAP_CELADON_CITY_GAME_CORNER_PRIZE_ROOM,
      group10_num16: MAP_CELADON_CITY_GYM,
      group10_num17: MAP_CELADON_CITY_RESTAURANT,
      group10_num18: MAP_CELADON_CITY_HOUSE1,
      group10_num19: MAP_CELADON_CITY_HOTEL,
      group11_num0: MAP_FUCHSIA_CITY_SAFARI_ZONE_ENTRANCE,
      group11_num1: MAP_FUCHSIA_CITY_MART,
      group11_num2: MAP_FUCHSIA_CITY_SAFARI_ZONE_OFFICE,
      group11_num3: MAP_FUCHSIA_CITY_GYM,
      group11_num4: MAP_FUCHSIA_CITY_HOUSE1,
      group11_num5: MAP_FUCHSIA_CITY_POKEMON_CENTER_1F,
      group11_num6: MAP_FUCHSIA_CITY_POKEMON_CENTER_2F,
      group11_num7: MAP_FUCHSIA_CITY_WARDENS_HOUSE,
      group11_num8: MAP_FUCHSIA_CITY_HOUSE2,
      group11_num9: MAP_FUCHSIA_CITY_HOUSE3,
      group12_num0: MAP_CINNABAR_ISLAND_GYM,
      group12_num1: MAP_CINNABAR_ISLAND_POKEMON_LAB_ENTRANCE,
      group12_num2: MAP_CINNABAR_ISLAND_POKEMON_LAB_LOUNGE,
      group12_num3: MAP_CINNABAR_ISLAND_POKEMON_LAB_RESEARCH_ROOM,
      group12_num4: MAP_CINNABAR_ISLAND_POKEMON_LAB_EXPERIMENT_ROOM,
      group12_num5: MAP_CINNABAR_ISLAND_POKEMON_CENTER_1F,
      group12_num6: MAP_CINNABAR_ISLAND_POKEMON_CENTER_2F,
      group12_num7: MAP_CINNABAR_ISLAND_MART,
      group13_num0: MAP_INDIGO_PLATEAU_POKEMON_CENTER_1F,
      group13_num1: MAP_INDIGO_PLATEAU_POKEMON_CENTER_2F,
      group14_num0: MAP_SAFFRON_CITY_COPYCATS_HOUSE_1F,
      group14_num1: MAP_SAFFRON_CITY_COPYCATS_HOUSE_2F,
      group14_num2: MAP_SAFFRON_CITY_DOJO,
      group14_num3: MAP_SAFFRON_CITY_GYM,
      group14_num4: MAP_SAFFRON_CITY_HOUSE,
      group14_num5: MAP_SAFFRON_CITY_MART,
      group14_num6: MAP_SAFFRON_CITY_POKEMON_CENTER_1F,
      group14_num7: MAP_SAFFRON_CITY_POKEMON_CENTER_2F,
      group14_num8: MAP_SAFFRON_CITY_MR_PSYCHICS_HOUSE,
      group14_num9: MAP_SAFFRON_CITY_POKEMON_TRAINER_FAN_CLUB,
      group15_num0: MAP_ROUTE2_VIRIDIAN_FOREST_SOUTH_ENTRANCE,
      group15_num1: MAP_ROUTE2_HOUSE,
      group15_num2: MAP_ROUTE2_EAST_BUILDING,
      group15_num3: MAP_ROUTE2_VIRIDIAN_FOREST_NORTH_ENTRANCE,
      group16_num0: MAP_ROUTE4_POKEMON_CENTER_1F,
      group16_num1: MAP_ROUTE4_POKEMON_CENTER_2F,
      group17_num0: MAP_ROUTE5_POKEMON_DAY_CARE,
      group17_num1: MAP_ROUTE5_SOUTH_ENTRANCE,
      group18_num0: MAP_ROUTE6_NORTH_ENTRANCE,
      group18_num1: MAP_ROUTE6_UNUSED_HOUSE,
      group19_num0: MAP_ROUTE7_EAST_ENTRANCE,
      group20_num0: MAP_ROUTE8_WEST_ENTRANCE,
      group21_num0: MAP_ROUTE10_POKEMON_CENTER_1F,
      group21_num1: MAP_ROUTE10_POKEMON_CENTER_2F,
      group22_num0: MAP_ROUTE11_EAST_ENTRANCE_1F,
      group22_num1: MAP_ROUTE11_EAST_ENTRANCE_2F,
      group23_num0: MAP_ROUTE12_NORTH_ENTRANCE_1F,
      group23_num1: MAP_ROUTE12_NORTH_ENTRANCE_2F,
      group23_num2: MAP_ROUTE12_FISHING_HOUSE,
      group24_num0: MAP_ROUTE15_WEST_ENTRANCE_1F,
      group24_num1: MAP_ROUTE15_WEST_ENTRANCE_2F,
      group25_num0: MAP_ROUTE16_HOUSE,
      group25_num1: MAP_ROUTE16_NORTH_ENTRANCE_1F,
      group25_num2: MAP_ROUTE16_NORTH_ENTRANCE_2F,
      group26_num0: MAP_ROUTE18_EAST_ENTRANCE_1F,
      group26_num1: MAP_ROUTE18_EAST_ENTRANCE_2F,
      group27_num0: MAP_ROUTE19_UNUSED_HOUSE,
      group28_num0: MAP_ROUTE22_NORTH_ENTRANCE,
      group29_num0: MAP_ROUTE23_UNUSED_HOUSE,
      group30_num0: MAP_ROUTE25_SEA_COTTAGE,
      group31_num0: MAP_SEVEN_ISLAND_HOUSE_ROOM1,
      group31_num1: MAP_SEVEN_ISLAND_HOUSE_ROOM2,
      group31_num2: MAP_SEVEN_ISLAND_MART,
      group31_num3: MAP_SEVEN_ISLAND_POKEMON_CENTER_1F,
      group31_num4: MAP_SEVEN_ISLAND_POKEMON_CENTER_2F,
      group31_num5: MAP_SEVEN_ISLAND_UNUSED_HOUSE,
      group31_num6: MAP_SEVEN_ISLAND_HARBOR,
      group32_num0: MAP_ONE_ISLAND_POKEMON_CENTER_1F,
      group32_num1: MAP_ONE_ISLAND_POKEMON_CENTER_2F,
      group32_num2: MAP_ONE_ISLAND_HOUSE1,
      group32_num3: MAP_ONE_ISLAND_HOUSE2,
      group32_num4: MAP_ONE_ISLAND_HARBOR,
      group33_num0: MAP_TWO_ISLAND_JOYFUL_GAME_CORNER,
      group33_num1: MAP_TWO_ISLAND_HOUSE,
      group33_num2: MAP_TWO_ISLAND_POKEMON_CENTER_1F,
      group33_num3: MAP_TWO_ISLAND_POKEMON_CENTER_2F,
      group33_num4: MAP_TWO_ISLAND_HARBOR,
      group34_num0: MAP_THREE_ISLAND_HOUSE1,
      group34_num1: MAP_THREE_ISLAND_POKEMON_CENTER_1F,
      group34_num2: MAP_THREE_ISLAND_POKEMON_CENTER_2F,
      group34_num3: MAP_THREE_ISLAND_MART,
      group34_num4: MAP_THREE_ISLAND_HOUSE2,
      group34_num5: MAP_THREE_ISLAND_HOUSE3,
      group34_num6: MAP_THREE_ISLAND_HOUSE4,
      group34_num7: MAP_THREE_ISLAND_HOUSE5,
      group35_num0: MAP_FOUR_ISLAND_POKEMON_DAY_CARE,
      group35_num1: MAP_FOUR_ISLAND_POKEMON_CENTER_1F,
      group35_num2: MAP_FOUR_ISLAND_POKEMON_CENTER_2F,
      group35_num3: MAP_FOUR_ISLAND_HOUSE1,
      group35_num4: MAP_FOUR_ISLAND_LORELEIS_HOUSE,
      group35_num5: MAP_FOUR_ISLAND_HARBOR,
      group35_num6: MAP_FOUR_ISLAND_HOUSE2,
      group35_num7: MAP_FOUR_ISLAND_MART,
      group36_num0: MAP_FIVE_ISLAND_POKEMON_CENTER_1F,
      group36_num1: MAP_FIVE_ISLAND_POKEMON_CENTER_2F,
      group36_num2: MAP_FIVE_ISLAND_HARBOR,
      group36_num3: MAP_FIVE_ISLAND_HOUSE1,
      group36_num4: MAP_FIVE_ISLAND_HOUSE2,
      group37_num0: MAP_SIX_ISLAND_POKEMON_CENTER_1F,
      group37_num1: MAP_SIX_ISLAND_POKEMON_CENTER_2F,
      group37_num2: MAP_SIX_ISLAND_HARBOR,
      group37_num3: MAP_SIX_ISLAND_HOUSE,
      group37_num4: MAP_SIX_ISLAND_MART,
      group38_num0: MAP_THREE_ISLAND_HARBOR,
      group39_num0: MAP_FIVE_ISLAND_RESORT_GORGEOUS_HOUSE,
      group40_num0: MAP_TWO_ISLAND_CAPE_BRINK_HOUSE,
      group41_num0: MAP_SIX_ISLAND_WATER_PATH_HOUSE1,
      group41_num1: MAP_SIX_ISLAND_WATER_PATH_HOUSE2,
      group42_num0: MAP_SEVEN_ISLAND_SEVAULT_CANYON_HOUSE
    }.freeze

    REVERSE_MAP_GROUP = {
      MAP_BATTLE_COLOSSEUM_2P: [0, 0],
      MAP_TRADE_CENTER: [0, 1],
      MAP_RECORD_CORNER: [0, 2],
      MAP_BATTLE_COLOSSEUM_4P: [0, 3],
      MAP_UNION_ROOM: [0, 4],
      MAP_VIRIDIAN_FOREST: [1, 0],
      MAP_MT_MOON_1F: [1, 1],
      MAP_MT_MOON_B1F: [1, 2],
      MAP_MT_MOON_B2F: [1, 3],
      MAP_SSANNE_EXTERIOR: [1, 4],
      MAP_SSANNE_1F_CORRIDOR: [1, 5],
      MAP_SSANNE_2F_CORRIDOR: [1, 6],
      MAP_SSANNE_3F_CORRIDOR: [1, 7],
      MAP_SSANNE_B1F_CORRIDOR: [1, 8],
      MAP_SSANNE_DECK: [1, 9],
      MAP_SSANNE_KITCHEN: [1, 10],
      MAP_SSANNE_CAPTAINS_OFFICE: [1, 11],
      MAP_SSANNE_1F_ROOM1: [1, 12],
      MAP_SSANNE_1F_ROOM2: [1, 13],
      MAP_SSANNE_1F_ROOM3: [1, 14],
      MAP_SSANNE_1F_ROOM4: [1, 15],
      MAP_SSANNE_1F_ROOM5: [1, 16],
      MAP_SSANNE_1F_ROOM7: [1, 17],
      MAP_SSANNE_2F_ROOM1: [1, 18],
      MAP_SSANNE_2F_ROOM2: [1, 19],
      MAP_SSANNE_2F_ROOM3: [1, 20],
      MAP_SSANNE_2F_ROOM4: [1, 21],
      MAP_SSANNE_2F_ROOM5: [1, 22],
      MAP_SSANNE_2F_ROOM6: [1, 23],
      MAP_SSANNE_B1F_ROOM1: [1, 24],
      MAP_SSANNE_B1F_ROOM2: [1, 25],
      MAP_SSANNE_B1F_ROOM3: [1, 26],
      MAP_SSANNE_B1F_ROOM4: [1, 27],
      MAP_SSANNE_B1F_ROOM5: [1, 28],
      MAP_SSANNE_1F_ROOM6: [1, 29],
      MAP_UNDERGROUND_PATH_NORTH_ENTRANCE: [1, 30],
      MAP_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL: [1, 31],
      MAP_UNDERGROUND_PATH_SOUTH_ENTRANCE: [1, 32],
      MAP_UNDERGROUND_PATH_WEST_ENTRANCE: [1, 33],
      MAP_UNDERGROUND_PATH_EAST_WEST_TUNNEL: [1, 34],
      MAP_UNDERGROUND_PATH_EAST_ENTRANCE: [1, 35],
      MAP_DIGLETTS_CAVE_NORTH_ENTRANCE: [1, 36],
      MAP_DIGLETTS_CAVE_B1F: [1, 37],
      MAP_DIGLETTS_CAVE_SOUTH_ENTRANCE: [1, 38],
      MAP_VICTORY_ROAD_1F: [1, 39],
      MAP_VICTORY_ROAD_2F: [1, 40],
      MAP_VICTORY_ROAD_3F: [1, 41],
      MAP_ROCKET_HIDEOUT_B1F: [1, 42],
      MAP_ROCKET_HIDEOUT_B2F: [1, 43],
      MAP_ROCKET_HIDEOUT_B3F: [1, 44],
      MAP_ROCKET_HIDEOUT_B4F: [1, 45],
      MAP_ROCKET_HIDEOUT_ELEVATOR: [1, 46],
      MAP_SILPH_CO_1F: [1, 47],
      MAP_SILPH_CO_2F: [1, 48],
      MAP_SILPH_CO_3F: [1, 49],
      MAP_SILPH_CO_4F: [1, 50],
      MAP_SILPH_CO_5F: [1, 51],
      MAP_SILPH_CO_6F: [1, 52],
      MAP_SILPH_CO_7F: [1, 53],
      MAP_SILPH_CO_8F: [1, 54],
      MAP_SILPH_CO_9F: [1, 55],
      MAP_SILPH_CO_10F: [1, 56],
      MAP_SILPH_CO_11F: [1, 57],
      MAP_SILPH_CO_ELEVATOR: [1, 58],
      MAP_POKEMON_MANSION_1F: [1, 59],
      MAP_POKEMON_MANSION_2F: [1, 60],
      MAP_POKEMON_MANSION_3F: [1, 61],
      MAP_POKEMON_MANSION_B1F: [1, 62],
      MAP_SAFARI_ZONE_CENTER: [1, 63],
      MAP_SAFARI_ZONE_EAST: [1, 64],
      MAP_SAFARI_ZONE_NORTH: [1, 65],
      MAP_SAFARI_ZONE_WEST: [1, 66],
      MAP_SAFARI_ZONE_CENTER_REST_HOUSE: [1, 67],
      MAP_SAFARI_ZONE_EAST_REST_HOUSE: [1, 68],
      MAP_SAFARI_ZONE_NORTH_REST_HOUSE: [1, 69],
      MAP_SAFARI_ZONE_WEST_REST_HOUSE: [1, 70],
      MAP_SAFARI_ZONE_SECRET_HOUSE: [1, 71],
      MAP_CERULEAN_CAVE_1F: [1, 72],
      MAP_CERULEAN_CAVE_2F: [1, 73],
      MAP_CERULEAN_CAVE_B1F: [1, 74],
      MAP_POKEMON_LEAGUE_LORELEIS_ROOM: [1, 75],
      MAP_POKEMON_LEAGUE_BRUNOS_ROOM: [1, 76],
      MAP_POKEMON_LEAGUE_AGATHAS_ROOM: [1, 77],
      MAP_POKEMON_LEAGUE_LANCES_ROOM: [1, 78],
      MAP_POKEMON_LEAGUE_CHAMPIONS_ROOM: [1, 79],
      MAP_POKEMON_LEAGUE_HALL_OF_FAME: [1, 80],
      MAP_ROCK_TUNNEL_1F: [1, 81],
      MAP_ROCK_TUNNEL_B1F: [1, 82],
      MAP_SEAFOAM_ISLANDS_1F: [1, 83],
      MAP_SEAFOAM_ISLANDS_B1F: [1, 84],
      MAP_SEAFOAM_ISLANDS_B2F: [1, 85],
      MAP_SEAFOAM_ISLANDS_B3F: [1, 86],
      MAP_SEAFOAM_ISLANDS_B4F: [1, 87],
      MAP_POKEMON_TOWER_1F: [1, 88],
      MAP_POKEMON_TOWER_2F: [1, 89],
      MAP_POKEMON_TOWER_3F: [1, 90],
      MAP_POKEMON_TOWER_4F: [1, 91],
      MAP_POKEMON_TOWER_5F: [1, 92],
      MAP_POKEMON_TOWER_6F: [1, 93],
      MAP_POKEMON_TOWER_7F: [1, 94],
      MAP_POWER_PLANT: [1, 95],
      MAP_MT_EMBER_RUBY_PATH_B4F: [1, 96],
      MAP_MT_EMBER_EXTERIOR: [1, 97],
      MAP_MT_EMBER_SUMMIT_PATH_1F: [1, 98],
      MAP_MT_EMBER_SUMMIT_PATH_2F: [1, 99],
      MAP_MT_EMBER_SUMMIT_PATH_3F: [1, 100],
      MAP_MT_EMBER_SUMMIT: [1, 101],
      MAP_MT_EMBER_RUBY_PATH_B5F: [1, 102],
      MAP_MT_EMBER_RUBY_PATH_1F: [1, 103],
      MAP_MT_EMBER_RUBY_PATH_B1F: [1, 104],
      MAP_MT_EMBER_RUBY_PATH_B2F: [1, 105],
      MAP_MT_EMBER_RUBY_PATH_B3F: [1, 106],
      MAP_MT_EMBER_RUBY_PATH_B1F_STAIRS: [1, 107],
      MAP_MT_EMBER_RUBY_PATH_B2F_STAIRS: [1, 108],
      MAP_THREE_ISLAND_BERRY_FOREST: [1, 109],
      MAP_FOUR_ISLAND_ICEFALL_CAVE_ENTRANCE: [1, 110],
      MAP_FOUR_ISLAND_ICEFALL_CAVE_1F: [1, 111],
      MAP_FOUR_ISLAND_ICEFALL_CAVE_B1F: [1, 112],
      MAP_FOUR_ISLAND_ICEFALL_CAVE_BACK: [1, 113],
      MAP_FIVE_ISLAND_ROCKET_WAREHOUSE: [1, 114],
      MAP_SIX_ISLAND_DOTTED_HOLE_1F: [1, 115],
      MAP_SIX_ISLAND_DOTTED_HOLE_B1F: [1, 116],
      MAP_SIX_ISLAND_DOTTED_HOLE_B2F: [1, 117],
      MAP_SIX_ISLAND_DOTTED_HOLE_B3F: [1, 118],
      MAP_SIX_ISLAND_DOTTED_HOLE_B4F: [1, 119],
      MAP_SIX_ISLAND_DOTTED_HOLE_SAPPHIRE_ROOM: [1, 120],
      MAP_SIX_ISLAND_PATTERN_BUSH: [1, 121],
      MAP_SIX_ISLAND_ALTERING_CAVE: [1, 122],
      MAP_NAVEL_ROCK_EXTERIOR: [2, 0],
      MAP_TRAINER_TOWER_1F: [2, 1],
      MAP_TRAINER_TOWER_2F: [2, 2],
      MAP_TRAINER_TOWER_3F: [2, 3],
      MAP_TRAINER_TOWER_4F: [2, 4],
      MAP_TRAINER_TOWER_5F: [2, 5],
      MAP_TRAINER_TOWER_6F: [2, 6],
      MAP_TRAINER_TOWER_7F: [2, 7],
      MAP_TRAINER_TOWER_8F: [2, 8],
      MAP_TRAINER_TOWER_ROOF: [2, 9],
      MAP_TRAINER_TOWER_LOBBY: [2, 10],
      MAP_TRAINER_TOWER_ELEVATOR: [2, 11],
      MAP_FIVE_ISLAND_LOST_CAVE_ENTRANCE: [2, 12],
      MAP_FIVE_ISLAND_LOST_CAVE_ROOM1: [2, 13],
      MAP_FIVE_ISLAND_LOST_CAVE_ROOM2: [2, 14],
      MAP_FIVE_ISLAND_LOST_CAVE_ROOM3: [2, 15],
      MAP_FIVE_ISLAND_LOST_CAVE_ROOM4: [2, 16],
      MAP_FIVE_ISLAND_LOST_CAVE_ROOM5: [2, 17],
      MAP_FIVE_ISLAND_LOST_CAVE_ROOM6: [2, 18],
      MAP_FIVE_ISLAND_LOST_CAVE_ROOM7: [2, 19],
      MAP_FIVE_ISLAND_LOST_CAVE_ROOM8: [2, 20],
      MAP_FIVE_ISLAND_LOST_CAVE_ROOM9: [2, 21],
      MAP_FIVE_ISLAND_LOST_CAVE_ROOM10: [2, 22],
      MAP_FIVE_ISLAND_LOST_CAVE_ROOM11: [2, 23],
      MAP_FIVE_ISLAND_LOST_CAVE_ROOM12: [2, 24],
      MAP_FIVE_ISLAND_LOST_CAVE_ROOM13: [2, 25],
      MAP_FIVE_ISLAND_LOST_CAVE_ROOM14: [2, 26],
      MAP_SEVEN_ISLAND_TANOBY_RUINS_MONEAN_CHAMBER: [2, 27],
      MAP_SEVEN_ISLAND_TANOBY_RUINS_LIPTOO_CHAMBER: [2, 28],
      MAP_SEVEN_ISLAND_TANOBY_RUINS_WEEPTH_CHAMBER: [2, 29],
      MAP_SEVEN_ISLAND_TANOBY_RUINS_DILFORD_CHAMBER: [2, 30],
      MAP_SEVEN_ISLAND_TANOBY_RUINS_SCUFIB_CHAMBER: [2, 31],
      MAP_SEVEN_ISLAND_TANOBY_RUINS_RIXY_CHAMBER: [2, 32],
      MAP_SEVEN_ISLAND_TANOBY_RUINS_VIAPOIS_CHAMBER: [2, 33],
      MAP_THREE_ISLAND_DUNSPARCE_TUNNEL: [2, 34],
      MAP_SEVEN_ISLAND_SEVAULT_CANYON_TANOBY_KEY: [2, 35],
      MAP_NAVEL_ROCK_1F: [2, 36],
      MAP_NAVEL_ROCK_SUMMIT: [2, 37],
      MAP_NAVEL_ROCK_BASE: [2, 38],
      MAP_NAVEL_ROCK_SUMMIT_PATH_2F: [2, 39],
      MAP_NAVEL_ROCK_SUMMIT_PATH_3F: [2, 40],
      MAP_NAVEL_ROCK_SUMMIT_PATH_4F: [2, 41],
      MAP_NAVEL_ROCK_SUMMIT_PATH_5F: [2, 42],
      MAP_NAVEL_ROCK_BASE_PATH_B1F: [2, 43],
      MAP_NAVEL_ROCK_BASE_PATH_B2F: [2, 44],
      MAP_NAVEL_ROCK_BASE_PATH_B3F: [2, 45],
      MAP_NAVEL_ROCK_BASE_PATH_B4F: [2, 46],
      MAP_NAVEL_ROCK_BASE_PATH_B5F: [2, 47],
      MAP_NAVEL_ROCK_BASE_PATH_B6F: [2, 48],
      MAP_NAVEL_ROCK_BASE_PATH_B7F: [2, 49],
      MAP_NAVEL_ROCK_BASE_PATH_B8F: [2, 50],
      MAP_NAVEL_ROCK_BASE_PATH_B9F: [2, 51],
      MAP_NAVEL_ROCK_BASE_PATH_B10F: [2, 52],
      MAP_NAVEL_ROCK_BASE_PATH_B11F: [2, 53],
      MAP_NAVEL_ROCK_B1F: [2, 54],
      MAP_NAVEL_ROCK_FORK: [2, 55],
      MAP_BIRTH_ISLAND_EXTERIOR: [2, 56],
      MAP_ONE_ISLAND_KINDLE_ROAD_EMBER_SPA: [2, 57],
      MAP_BIRTH_ISLAND_HARBOR: [2, 58],
      MAP_NAVEL_ROCK_HARBOR: [2, 59],
      MAP_PALLET_TOWN: [3, 0],
      MAP_VIRIDIAN_CITY: [3, 1],
      MAP_PEWTER_CITY: [3, 2],
      MAP_CERULEAN_CITY: [3, 3],
      MAP_LAVENDER_TOWN: [3, 4],
      MAP_VERMILION_CITY: [3, 5],
      MAP_CELADON_CITY: [3, 6],
      MAP_FUCHSIA_CITY: [3, 7],
      MAP_CINNABAR_ISLAND: [3, 8],
      MAP_INDIGO_PLATEAU_EXTERIOR: [3, 9],
      MAP_SAFFRON_CITY: [3, 10],
      MAP_SAFFRON_CITY_CONNECTION: [3, 11],
      MAP_ONE_ISLAND: [3, 12],
      MAP_TWO_ISLAND: [3, 13],
      MAP_THREE_ISLAND: [3, 14],
      MAP_FOUR_ISLAND: [3, 15],
      MAP_FIVE_ISLAND: [3, 16],
      MAP_SEVEN_ISLAND: [3, 17],
      MAP_SIX_ISLAND: [3, 18],
      MAP_ROUTE1: [3, 19],
      MAP_ROUTE2: [3, 20],
      MAP_ROUTE3: [3, 21],
      MAP_ROUTE4: [3, 22],
      MAP_ROUTE5: [3, 23],
      MAP_ROUTE6: [3, 24],
      MAP_ROUTE7: [3, 25],
      MAP_ROUTE8: [3, 26],
      MAP_ROUTE9: [3, 27],
      MAP_ROUTE10: [3, 28],
      MAP_ROUTE11: [3, 29],
      MAP_ROUTE12: [3, 30],
      MAP_ROUTE13: [3, 31],
      MAP_ROUTE14: [3, 32],
      MAP_ROUTE15: [3, 33],
      MAP_ROUTE16: [3, 34],
      MAP_ROUTE17: [3, 35],
      MAP_ROUTE18: [3, 36],
      MAP_ROUTE19: [3, 37],
      MAP_ROUTE20: [3, 38],
      MAP_ROUTE21_NORTH: [3, 39],
      MAP_ROUTE21_SOUTH: [3, 40],
      MAP_ROUTE22: [3, 41],
      MAP_ROUTE23: [3, 42],
      MAP_ROUTE24: [3, 43],
      MAP_ROUTE25: [3, 44],
      MAP_ONE_ISLAND_KINDLE_ROAD: [3, 45],
      MAP_ONE_ISLAND_TREASURE_BEACH: [3, 46],
      MAP_TWO_ISLAND_CAPE_BRINK: [3, 47],
      MAP_THREE_ISLAND_BOND_BRIDGE: [3, 48],
      MAP_THREE_ISLAND_PORT: [3, 49],
      MAP_PROTOTYPE_SEVII_ISLE_6: [3, 50],
      MAP_PROTOTYPE_SEVII_ISLE_7: [3, 51],
      MAP_PROTOTYPE_SEVII_ISLE_8: [3, 52],
      MAP_PROTOTYPE_SEVII_ISLE_9: [3, 53],
      MAP_FIVE_ISLAND_RESORT_GORGEOUS: [3, 54],
      MAP_FIVE_ISLAND_WATER_LABYRINTH: [3, 55],
      MAP_FIVE_ISLAND_MEADOW: [3, 56],
      MAP_FIVE_ISLAND_MEMORIAL_PILLAR: [3, 57],
      MAP_SIX_ISLAND_OUTCAST_ISLAND: [3, 58],
      MAP_SIX_ISLAND_GREEN_PATH: [3, 59],
      MAP_SIX_ISLAND_WATER_PATH: [3, 60],
      MAP_SIX_ISLAND_RUIN_VALLEY: [3, 61],
      MAP_SEVEN_ISLAND_TRAINER_TOWER: [3, 62],
      MAP_SEVEN_ISLAND_SEVAULT_CANYON_ENTRANCE: [3, 63],
      MAP_SEVEN_ISLAND_SEVAULT_CANYON: [3, 64],
      MAP_SEVEN_ISLAND_TANOBY_RUINS: [3, 65],
      MAP_PALLET_TOWN_PLAYERS_HOUSE_1F: [4, 0],
      MAP_PALLET_TOWN_PLAYERS_HOUSE_2F: [4, 1],
      MAP_PALLET_TOWN_RIVALS_HOUSE: [4, 2],
      MAP_PALLET_TOWN_PROFESSOR_OAKS_LAB: [4, 3],
      MAP_VIRIDIAN_CITY_HOUSE: [5, 0],
      MAP_VIRIDIAN_CITY_GYM: [5, 1],
      MAP_VIRIDIAN_CITY_SCHOOL: [5, 2],
      MAP_VIRIDIAN_CITY_MART: [5, 3],
      MAP_VIRIDIAN_CITY_POKEMON_CENTER_1F: [5, 4],
      MAP_VIRIDIAN_CITY_POKEMON_CENTER_2F: [5, 5],
      MAP_PEWTER_CITY_MUSEUM_1F: [6, 0],
      MAP_PEWTER_CITY_MUSEUM_2F: [6, 1],
      MAP_PEWTER_CITY_GYM: [6, 2],
      MAP_PEWTER_CITY_MART: [6, 3],
      MAP_PEWTER_CITY_HOUSE1: [6, 4],
      MAP_PEWTER_CITY_POKEMON_CENTER_1F: [6, 5],
      MAP_PEWTER_CITY_POKEMON_CENTER_2F: [6, 6],
      MAP_PEWTER_CITY_HOUSE2: [6, 7],
      MAP_CERULEAN_CITY_HOUSE1: [7, 0],
      MAP_CERULEAN_CITY_HOUSE2: [7, 1],
      MAP_CERULEAN_CITY_HOUSE3: [7, 2],
      MAP_CERULEAN_CITY_POKEMON_CENTER_1F: [7, 3],
      MAP_CERULEAN_CITY_POKEMON_CENTER_2F: [7, 4],
      MAP_CERULEAN_CITY_GYM: [7, 5],
      MAP_CERULEAN_CITY_BIKE_SHOP: [7, 6],
      MAP_CERULEAN_CITY_MART: [7, 7],
      MAP_CERULEAN_CITY_HOUSE4: [7, 8],
      MAP_CERULEAN_CITY_HOUSE5: [7, 9],
      MAP_LAVENDER_TOWN_POKEMON_CENTER_1F: [8, 0],
      MAP_LAVENDER_TOWN_POKEMON_CENTER_2F: [8, 1],
      MAP_LAVENDER_TOWN_VOLUNTEER_POKEMON_HOUSE: [8, 2],
      MAP_LAVENDER_TOWN_HOUSE1: [8, 3],
      MAP_LAVENDER_TOWN_HOUSE2: [8, 4],
      MAP_LAVENDER_TOWN_MART: [8, 5],
      MAP_VERMILION_CITY_HOUSE1: [9, 0],
      MAP_VERMILION_CITY_POKEMON_CENTER_1F: [9, 1],
      MAP_VERMILION_CITY_POKEMON_CENTER_2F: [9, 2],
      MAP_VERMILION_CITY_POKEMON_FAN_CLUB: [9, 3],
      MAP_VERMILION_CITY_HOUSE2: [9, 4],
      MAP_VERMILION_CITY_MART: [9, 5],
      MAP_VERMILION_CITY_GYM: [9, 6],
      MAP_VERMILION_CITY_HOUSE3: [9, 7],
      MAP_CELADON_CITY_DEPARTMENT_STORE_1F: [10, 0],
      MAP_CELADON_CITY_DEPARTMENT_STORE_2F: [10, 1],
      MAP_CELADON_CITY_DEPARTMENT_STORE_3F: [10, 2],
      MAP_CELADON_CITY_DEPARTMENT_STORE_4F: [10, 3],
      MAP_CELADON_CITY_DEPARTMENT_STORE_5F: [10, 4],
      MAP_CELADON_CITY_DEPARTMENT_STORE_ROOF: [10, 5],
      MAP_CELADON_CITY_DEPARTMENT_STORE_ELEVATOR: [10, 6],
      MAP_CELADON_CITY_CONDOMINIUMS_1F: [10, 7],
      MAP_CELADON_CITY_CONDOMINIUMS_2F: [10, 8],
      MAP_CELADON_CITY_CONDOMINIUMS_3F: [10, 9],
      MAP_CELADON_CITY_CONDOMINIUMS_ROOF: [10, 10],
      MAP_CELADON_CITY_CONDOMINIUMS_ROOF_ROOM: [10, 11],
      MAP_CELADON_CITY_POKEMON_CENTER_1F: [10, 12],
      MAP_CELADON_CITY_POKEMON_CENTER_2F: [10, 13],
      MAP_CELADON_CITY_GAME_CORNER: [10, 14],
      MAP_CELADON_CITY_GAME_CORNER_PRIZE_ROOM: [10, 15],
      MAP_CELADON_CITY_GYM: [10, 16],
      MAP_CELADON_CITY_RESTAURANT: [10, 17],
      MAP_CELADON_CITY_HOUSE1: [10, 18],
      MAP_CELADON_CITY_HOTEL: [10, 19],
      MAP_FUCHSIA_CITY_SAFARI_ZONE_ENTRANCE: [11, 0],
      MAP_FUCHSIA_CITY_MART: [11, 1],
      MAP_FUCHSIA_CITY_SAFARI_ZONE_OFFICE: [11, 2],
      MAP_FUCHSIA_CITY_GYM: [11, 3],
      MAP_FUCHSIA_CITY_HOUSE1: [11, 4],
      MAP_FUCHSIA_CITY_POKEMON_CENTER_1F: [11, 5],
      MAP_FUCHSIA_CITY_POKEMON_CENTER_2F: [11, 6],
      MAP_FUCHSIA_CITY_WARDENS_HOUSE: [11, 7],
      MAP_FUCHSIA_CITY_HOUSE2: [11, 8],
      MAP_FUCHSIA_CITY_HOUSE3: [11, 9],
      MAP_CINNABAR_ISLAND_GYM: [12, 0],
      MAP_CINNABAR_ISLAND_POKEMON_LAB_ENTRANCE: [12, 1],
      MAP_CINNABAR_ISLAND_POKEMON_LAB_LOUNGE: [12, 2],
      MAP_CINNABAR_ISLAND_POKEMON_LAB_RESEARCH_ROOM: [12, 3],
      MAP_CINNABAR_ISLAND_POKEMON_LAB_EXPERIMENT_ROOM: [12, 4],
      MAP_CINNABAR_ISLAND_POKEMON_CENTER_1F: [12, 5],
      MAP_CINNABAR_ISLAND_POKEMON_CENTER_2F: [12, 6],
      MAP_CINNABAR_ISLAND_MART: [12, 7],
      MAP_INDIGO_PLATEAU_POKEMON_CENTER_1F: [13, 0],
      MAP_INDIGO_PLATEAU_POKEMON_CENTER_2F: [13, 1],
      MAP_SAFFRON_CITY_COPYCATS_HOUSE_1F: [14, 0],
      MAP_SAFFRON_CITY_COPYCATS_HOUSE_2F: [14, 1],
      MAP_SAFFRON_CITY_DOJO: [14, 2],
      MAP_SAFFRON_CITY_GYM: [14, 3],
      MAP_SAFFRON_CITY_HOUSE: [14, 4],
      MAP_SAFFRON_CITY_MART: [14, 5],
      MAP_SAFFRON_CITY_POKEMON_CENTER_1F: [14, 6],
      MAP_SAFFRON_CITY_POKEMON_CENTER_2F: [14, 7],
      MAP_SAFFRON_CITY_MR_PSYCHICS_HOUSE: [14, 8],
      MAP_SAFFRON_CITY_POKEMON_TRAINER_FAN_CLUB: [14, 9],
      MAP_ROUTE2_VIRIDIAN_FOREST_SOUTH_ENTRANCE: [15, 0],
      MAP_ROUTE2_HOUSE: [15, 1],
      MAP_ROUTE2_EAST_BUILDING: [15, 2],
      MAP_ROUTE2_VIRIDIAN_FOREST_NORTH_ENTRANCE: [15, 3],
      MAP_ROUTE4_POKEMON_CENTER_1F: [16, 0],
      MAP_ROUTE4_POKEMON_CENTER_2F: [16, 1],
      MAP_ROUTE5_POKEMON_DAY_CARE: [17, 0],
      MAP_ROUTE5_SOUTH_ENTRANCE: [17, 1],
      MAP_ROUTE6_NORTH_ENTRANCE: [18, 0],
      MAP_ROUTE6_UNUSED_HOUSE: [18, 1],
      MAP_ROUTE7_EAST_ENTRANCE: [19, 0],
      MAP_ROUTE8_WEST_ENTRANCE: [20, 0],
      MAP_ROUTE10_POKEMON_CENTER_1F: [21, 0],
      MAP_ROUTE10_POKEMON_CENTER_2F: [21, 1],
      MAP_ROUTE11_EAST_ENTRANCE_1F: [22, 0],
      MAP_ROUTE11_EAST_ENTRANCE_2F: [22, 1],
      MAP_ROUTE12_NORTH_ENTRANCE_1F: [23, 0],
      MAP_ROUTE12_NORTH_ENTRANCE_2F: [23, 1],
      MAP_ROUTE12_FISHING_HOUSE: [23, 2],
      MAP_ROUTE15_WEST_ENTRANCE_1F: [24, 0],
      MAP_ROUTE15_WEST_ENTRANCE_2F: [24, 1],
      MAP_ROUTE16_HOUSE: [25, 0],
      MAP_ROUTE16_NORTH_ENTRANCE_1F: [25, 1],
      MAP_ROUTE16_NORTH_ENTRANCE_2F: [25, 2],
      MAP_ROUTE18_EAST_ENTRANCE_1F: [26, 0],
      MAP_ROUTE18_EAST_ENTRANCE_2F: [26, 1],
      MAP_ROUTE19_UNUSED_HOUSE: [27, 0],
      MAP_ROUTE22_NORTH_ENTRANCE: [28, 0],
      MAP_ROUTE23_UNUSED_HOUSE: [29, 0],
      MAP_ROUTE25_SEA_COTTAGE: [30, 0],
      MAP_SEVEN_ISLAND_HOUSE_ROOM1: [31, 0],
      MAP_SEVEN_ISLAND_HOUSE_ROOM2: [31, 1],
      MAP_SEVEN_ISLAND_MART: [31, 2],
      MAP_SEVEN_ISLAND_POKEMON_CENTER_1F: [31, 3],
      MAP_SEVEN_ISLAND_POKEMON_CENTER_2F: [31, 4],
      MAP_SEVEN_ISLAND_UNUSED_HOUSE: [31, 5],
      MAP_SEVEN_ISLAND_HARBOR: [31, 6],
      MAP_ONE_ISLAND_POKEMON_CENTER_1F: [32, 0],
      MAP_ONE_ISLAND_POKEMON_CENTER_2F: [32, 1],
      MAP_ONE_ISLAND_HOUSE1: [32, 2],
      MAP_ONE_ISLAND_HOUSE2: [32, 3],
      MAP_ONE_ISLAND_HARBOR: [32, 4],
      MAP_TWO_ISLAND_JOYFUL_GAME_CORNER: [33, 0],
      MAP_TWO_ISLAND_HOUSE: [33, 1],
      MAP_TWO_ISLAND_POKEMON_CENTER_1F: [33, 2],
      MAP_TWO_ISLAND_POKEMON_CENTER_2F: [33, 3],
      MAP_TWO_ISLAND_HARBOR: [33, 4],
      MAP_THREE_ISLAND_HOUSE1: [34, 0],
      MAP_THREE_ISLAND_POKEMON_CENTER_1F: [34, 1],
      MAP_THREE_ISLAND_POKEMON_CENTER_2F: [34, 2],
      MAP_THREE_ISLAND_MART: [34, 3],
      MAP_THREE_ISLAND_HOUSE2: [34, 4],
      MAP_THREE_ISLAND_HOUSE3: [34, 5],
      MAP_THREE_ISLAND_HOUSE4: [34, 6],
      MAP_THREE_ISLAND_HOUSE5: [34, 7],
      MAP_FOUR_ISLAND_POKEMON_DAY_CARE: [35, 0],
      MAP_FOUR_ISLAND_POKEMON_CENTER_1F: [35, 1],
      MAP_FOUR_ISLAND_POKEMON_CENTER_2F: [35, 2],
      MAP_FOUR_ISLAND_HOUSE1: [35, 3],
      MAP_FOUR_ISLAND_LORELEIS_HOUSE: [35, 4],
      MAP_FOUR_ISLAND_HARBOR: [35, 5],
      MAP_FOUR_ISLAND_HOUSE2: [35, 6],
      MAP_FOUR_ISLAND_MART: [35, 7],
      MAP_FIVE_ISLAND_POKEMON_CENTER_1F: [36, 0],
      MAP_FIVE_ISLAND_POKEMON_CENTER_2F: [36, 1],
      MAP_FIVE_ISLAND_HARBOR: [36, 2],
      MAP_FIVE_ISLAND_HOUSE1: [36, 3],
      MAP_FIVE_ISLAND_HOUSE2: [36, 4],
      MAP_SIX_ISLAND_POKEMON_CENTER_1F: [37, 0],
      MAP_SIX_ISLAND_POKEMON_CENTER_2F: [37, 1],
      MAP_SIX_ISLAND_HARBOR: [37, 2],
      MAP_SIX_ISLAND_HOUSE: [37, 3],
      MAP_SIX_ISLAND_MART: [37, 4],
      MAP_THREE_ISLAND_HARBOR: [38, 0],
      MAP_FIVE_ISLAND_RESORT_GORGEOUS_HOUSE: [39, 0],
      MAP_TWO_ISLAND_CAPE_BRINK_HOUSE: [40, 0],
      MAP_SIX_ISLAND_WATER_PATH_HOUSE1: [41, 0],
      MAP_SIX_ISLAND_WATER_PATH_HOUSE2: [41, 1],
      MAP_SEVEN_ISLAND_SEVAULT_CANYON_HOUSE: [42, 0]
    }.freeze
  end
end
